import pokemonNames from '../data/pokemonNames.json';
import packNames from '../data/packNames.json';

interface PokemonName {
  id: number;
  ko: string;
  ja: string;
  en: string;
}

interface PackName {
  code: string;
  ja: string;
  ko: string;
}

// 긴 이름부터 치환해야 "Mew"가 "Mewtwo" 안에서 먼저 걸려 이름이 깨지는 걸 막을 수 있다.
// (koreanizeTitle의 일본어 처리, translateQueryToEnglish의 한글 처리와 같은 방식)
const sortedPokemonEnKo = (pokemonNames as PokemonName[])
  .filter((entry) => entry.en && entry.ko)
  .sort((a, b) => b.en.length - a.en.length);

const packKoByCode = new Map(
  (packNames as PackName[]).filter((entry) => entry.code && entry.ko).map((entry) => [entry.code.toLowerCase(), entry.ko]),
);

// 포켓몬 이름 앞에 붙는 수식어. "ex"/"V"/"VMAX"/"GX" 같은 접미사는 한국 공식 표기에서도
// 영문 그대로 쓰기 때문에 건드리지 않는다.
const STRUCTURAL_EN_TO_KO: [string, string][] = [
  // 소유격 카드명(Destined Rivals 등). 함수 초입에서 곧은 어포스트로피(')를 굽은
  // 것(’)으로 정규화하므로 여기 키도 굽은 표기다. 한글명은 전부 기존 트레이너
  // 사전에서 확정된 이름만 쓴다.
  ['Team Rocket’s ', '로켓단의 '],
  ['Ethan’s ', '심향의 '],
  ['Misty’s ', '이슬의 '],
  ['Cynthia’s ', '난천의 '],
  ['Steven’s ', '성호의 '],
  ['Arven’s ', '페퍼의 '],
  ['Marnie’s ', '마리의 '],
  ['Lillie’s ', '릴리에의 '],
  ['N’s ', 'N의 '],
  ['Iono’s ', '모야모의 '],
  ['Hop’s ', '호프의 '],
  ['Mega ', '메가'],
  ['Radiant ', '찬란한 '], // かがやく/輝く의 영문판. koreanizeTitle과 같은 표기로 맞춘다.
  // 지역폼 접두사. 뒤의 포켓몬 이름은 사전 치환으로 한글이 되고, 이 접두사만 남던 걸
  // 한글 공식 표기로 바꾼다. 예: "Galarian Mr. Mime" → "가라르 마임맨".
  ['Galarian ', '가라르 '],
  ['Alolan ', '알로라 '],
  ['Hisuian ', '히스이 '],
  ['Paldean ', '팔데아 '],
];

// 트레이너·인물 서포트 카드 이름(영어 → 한글). 포켓몬이 아니라 pokemonNames 사전에 없어
// 그동안 영문으로 남았다. 한글은 공식 한국 포켓몬 표기(koreanizeTitle의 일본어쪽과 동일).
// ⚠️ "N"·"Red"처럼 짧은 이름이 다른 단어 안에 끼지 않도록, 카드명 "전체"가 정확히
// 일치할 때만 바꾼다(부분 치환 안 함).
const TRAINER_EN_TO_KO: Record<string, string> = {
  Serena: '세레나',
  Cynthia: '난천', // シロナ. 일본어 음역 "시로나"가 아니라 한국 정식명 "난천".
  Marnie: '마리',
  Lillie: '릴리에',
  Sabrina: '초련', // ナツメ (나츠메는 일본명)
  Iono: '모야모', // ナンジャモ. 난자모는 흔한 오표기, 공식은 모야모
  Nemona: '네모',
  Arven: '페퍼',
  // Penny(ボタン)의 공식 한글명은 '모란'이다. '보탄'은 일본 이름 음역이라 틀렸다.
  Penny: '모란',
  Clavell: '클라벨', // クラベル (청목은 Larry 이름이라 오류)
  Bianca: '벨',
  Cheren: '체렌',
  Hop: '호프',
  Leon: '단델',
  Sonia: '소니아',
  Nessa: '야청', // ルリナ
  Piers: '두송', // ネズ, 스파이크타운 악 관장 (네즈는 일본명)
  Roxie: '보미카',
  Rosa: '명희',
  Grusha: '그루샤',
  Acerola: '아세로라',
  Wally: '민진',
  Lance: '목호',
  Blaine: '강연',
  Misty: '이슬',
  Ash: '지우',
  "Professor's Research": '박사의 연구',
  "Brock's Scouting": '웅의 스카우트',
  Levincia: '누룩스시티',
  "Boss's Orders": '보스의 지령',
  // Atticus = シュウメイ = 추명. 효과문이 완전히 같아 확정했다(SV8a シュウメイ:
  // "상대 배틀 포켓몬이 독일 때만 쓸 수 있다 … 패를 덱에 되돌려 섞고 7장 뽑는다"
  // ↔ Atticus: "opponent's Active Pokémon is Poisoned … draw 7 cards").
  Atticus: '추명',
  'Forest of Vitality': '활력의 숲',
  // 추가 인물(확신하는 공식 표기만). 갈라르 관장 등 불확실한 이름은 넣지 않는다
  // — 틀린 한글보다 영어가 낫다.
  Guzma: '구즈마',
  Lusamine: '루자미네',
  Lysandre: '플라드리',
  Hau: '하우',
  Rose: '로즈',
  Oleana: '올리브',
  Bea: '채두', // サイトウ, 가라르 격투 관장 (사요는 오역)
  Brawly: '철구', // トウキ (텟센은 Wattson의 일본명이라 오류였음)
  Wattson: '암페어', // テッセン
  Flannery: '민지', // アスナ
  Juan: '아단', // アダン
  Sidney: '혁진', // カゲツ, 악 사천왕
  Glacia: '미혜', // プリム, 얼음 사천왕
  Drake: '권수', // ゲンジ, 드래곤 사천왕
  Opal: '포플러', // ポプラ (포푸라는 일본명)
  Shauna: '사나',
  Skyla: '풍란', // フウロ (후우로는 일본명)
  Hala: '할라',
  Milo: '야로우', // ヤロー, 터프필드 풀 관장
  Agatha: '국화', // キクコ (오바는 오역)
  Bruno: '시바',
  Erika: '민화', // エリカ (에리카는 일본명)
  Kiawe: '키아웨', // カキ (카키는 일본명)
  Sophocles: '마마네',
  Volkner: '전진', // デンジ (덴지는 일본명)
  Phoebe: '회연', // フヨウ (후요는 일본명)
  Cheryl: '모미',
  Candice: '무청', // スズナ (스즈나는 일본명)
  Gardenia: '유채', // ナタネ (나타네는 일본명)
  Grant: '자크로', // ザクロ (자쿠로는 일본명)
  Korrina: '코르니',
  Tierno: '티에르노',
  Hilda: '투희', // ヒルダ (히루다는 일본명)
  'Professor Sycamore': '플라타느박사',
  'Professor Juniper': '아라라기박사',
  'Team Yell Grunt': '옐 단원',
  'Team Flare Grunt': '플레어단 단원',
  'Team Rocket Grunt': '로켓단 단원',
  // 번역 점검 배치: 공식 한글명 확인된 관장·챔피언·악당보스.
  Brock: '웅',
  Steven: '성호',
  Wallace: '윤진',
  Giovanni: '비주기',
  Cyrus: '태홍',
  Ghetsis: '게치스',
  'Lt. Surge': '마티스',
  Maylene: '자두',
  Diantha: '카르네',
  Alder: '노간주',
  Iris: '아이리스',
  // 번역 점검 2차: 성도·호연 관장/사천왕/악당보스(공식 한글명 확인).
  Falkner: '비상',
  Bugsy: '호일',
  Whitney: '꼭두',
  Morty: '유빈',
  Chuck: '사도',
  Jasmine: '규리',
  Pryce: '류옹',
  Clair: '이향',
  Koga: '독수',
  Janine: '도희',
  Lorelei: '칸나',
  Will: '일목',
  Karen: '카렌',
  Colress: '아크로마',
  Maxie: '마적',
  Archie: '아강',
  // 번역 점검 3차: 사용자 확인 + 검증한 관장/라이벌.
  Barry: '용식', // ジュン, 신오 라이벌
  Norman: '종길', // センリ, 무궁시티 노말 관장
  Winona: '은송', // ナギ, 검방울시티 비행 관장 (이전 "원규"는 Roark 이름이라 수정)
  Roark: '강석', // ヒョウタ, 광연시티 바위 관장
  Roxanne: '원규', // ツツジ, 호연 바위 관장 (사용자가 Roark로 준 "원규"의 실제 주인)
  'Crasher Wake': '맥실러', // マキシ, 연화시티 물 관장
  Elesa: '카밀레', // カミツレ, 뇌엔시티 전기 관장
  Clay: '야콘', // ヤーコン, 물풍경시티 땅 관장 (아콘은 오타)
  // 번역 점검 5차: 하나·칼로스 관장/사천왕 (Fandom 리그 공식표).
  Cilan: '덴트',
  Chili: '팟',
  Cress: '콘',
  Lenora: '알로에',
  Burgh: '아티',
  Brycen: '담죽',
  Drayden: '사간',
  Marlon: '시즈',
  Shauntal: '망초',
  Marshal: '연무',
  Grimsley: '블래리',
  Caitlin: '카틀레야',
  Viola: '비올라',
  Ramos: '후쿠지',
  Clemont: '시트론',
  Wulfric: '우르프',
  Aaron: '충호', // 신오 벌레 사천왕
  Bertha: '들국화', // 신오 땅 사천왕
  Flint: '대엽', // 신오 불꽃 사천왕
  Lucian: '오엽', // 신오 에스퍼 사천왕
  Byron: '동관', // 신오 강철 관장
  Fantina: '멜리사', // 신오 고스트 관장
  // 번역 점검 6차: 팔데아 관장/사천왕 + 칼로스 사천왕.
  Katy: '단풍',
  Brassius: '콜사',
  Kofu: '곤포',
  Larry: '청목', // アオキ, 노말 관장 겸 비행 사천왕
  Ryme: '라임',
  Tulip: '리파',
  Rika: '칠리',
  // 아래는 일본어 사전에서 이미 확인된 공식 한글명을 영문판 경로에도 맞춘 것.
  // (영문 카드에서 이름이 영어 그대로 뜨던 인물들)
  Melony: '멜론',
  Raihan: '금랑',
  Jacq: '지니어',
  Miriam: '미모사',
  Saguaro: '사구아로',
  Poppy: '뽀삐',
  Hassel: '팔자크',
  Geeta: '테사',
  Malva: '파키라',
  Siebold: '즈미',
  Wikstrom: '간피',
  Drasna: '드라세나',
  // 알로라 캡틴 + 갤럭시단 간부.
  Ilima: '일리마',
  Lana: '수련',
  Mallow: '마오',
  Mina: '말리화',
  Mars: '마스',
  Jupiter: '주피터',
  Saturn: '새턴',
  Charon: '플루토',
  Allister: '어니언', // 가라르 고스트 관장
  Bede: '비트', // 가라르
  Kieran: '카지', // 벽록의 가면 (시유의 남동생)
  Briar: '브라이어', // SV
  Mela: '멜로코', // 팀 스타 보스
  Eri: '비파', // 팀 스타 보스
  Ortega: '오르티가', // 팀 스타 보스
  Giacomo: '피나', // 팀 스타 악 보스
  // 플레어단 간부 + 스컬단.
  Aliana: '아케비',
  Celosia: '코레아',
  Mable: '바라',
  Bryony: '모미지',
  Xerosic: '크세로시키',
  Plumeria: '플루메리',
  Gladion: '글라디오', // 릴리에의 오빠
  Faba: '자우보', // 에테르재단
  Hapu: '하푸우', // 포니섬 왕
  Blue: '그린', // グリーン. 북미판만 Blue, 한국/일본은 그린
  Molayne: '머마네',
  Kahili: '카히리',
  Wicke: '비커', // 에테르재단 비서
  // 히스이 (레전드 아르세우스).
  Volo: '월로',
  Drayton: '제빈',
  Perrin: '세류',
  Crispin: '하솔',
  Adaman: '찬석', // 공식 카드로 확인(류가 아님)
  Irida: '주혜',
  Cyllene: '금경', // 조사대장. 공식 카드 S9a로 확인(경단·찬석 아님)
  Kamado: '전목', // 공식 카드 S9a로 확인(파래열 아님)
  Mai: '마이',
  Laventon: '라벤',
  Valerie: '마슈', // マーシュ, 후늬시티 페어리 관장 (마수드는 오역)
  Olympia: '고지카', // ゴジカ, 별록시티 에스퍼 관장
  Olivia: '라이치', // ライチ, 아칼라섬 도주 바위
  Nanu: '나루화', // ナリヤ, 울라울라섬 도주 악
};

// 아이템·에너지·화석·일반 역할 카드(영어 → 한글). 공식 한국 포켓몬 카드 표기.
// 카드명 "전체"가 정확히 일치할 때만 바꾼다.
const ITEM_EN_TO_KO: Record<string, string> = {
  // ── 사용자가 확인해 준 공식 한글 카드명 621개(2026-07-26) ────────────────
  // 한국 공식 포켓몬 카드 게임 데이터베이스 기준. SV·SWSH·SM·XY·BW·구세대의
  // 트레이너스·스타디움·굿즈·특수에너지가 섞여 있다(둘 다 같은 방식으로 쓰이므로
  // 표를 나누지 않았다). 이름이 겹치거나 한글이 아닌 45개는 넣지 않고 되물었다.
  'Academy at Night': '야간 학원',
  'Ancient Booster Energy Capsule': '부스트에너지 고대',
  'Antique Plume Fossil': '복원된 깃털카세키',
  'Awakening Drum': '각성의 드럼',
  'Beach Court': '해변의 코트',
  'Boxed Order': '박스 주문',
  'Brave Bangle': '용기의 뱅글',
  'Calamitous Snowy Mountain': '재앙의 설산',
  'Calamitous Wasteland': '재앙의 황야',
  Cassiopeia: '카시오페아',
  Clive: '클라브',
  'Counter Catcher': '카운터 캐처',
  'Cursed Duster': '원한의 먼지털이',
  'Dangerous Laser': '데인저러스 레이저',
  'Defiance Band': '반격의 머리띠',
  'Defiance Vest': '반격의 조끼',
  'Delivery Drone': '배달 드론',
  'Electric Generator': '일렉트릭제네레이터',
  'Energy Coin': '에너지 코인',
  'Exp. Share': '학습장치',
  Fennel: '회향',
  'Fighting Au Lait': '격투 맛의 오레',
  'Full Metal Lab': '풀메탈랩',
  'Future Booster Energy Capsule': '부스트에너지 미래',
  'Hand Trimmer': '핸드트리머',
  Harlequin: '피에로',
  'Heavy Baton': '헤비바톤',
  'Ignition Energy': '점화 에너지',
  'Luxurious Cape': '호화로운 망토',
  'Medical Energy': '메디컬 에너지',
  Mesagoza: '테이블시티',
  'Mist Energy': '미스트 에너지',
  'Moonlit Hill': '달맞이 언덕',
  'Neo Upper Energy': '네오 어퍼 에너지',
  'Neutralization Zone': '널리파이어 존',
  'Paradise Resort': '파라다이스 리조트',
  'Parasol Lady': '파라솔 누나',
  'Perilous Jungle': '위협의 정글',
  'Picnic Basket': '피크닉 바스켓',
  'Poké Vital A': '포케바이탈A',
  Powerglass: '파워글라스',
  'Practice Studio': '연습 스튜디오',
  'Prism Energy': '프리즘 에너지',
  'Reboot Pod': '리부트 포드',
  'Reversal Energy': '리버스 에너지',
  'Rock Chestplate': '암석의 가슴받이',
  Salvatore: '세이지',
  'Technical Machine: Blindside': '기술머신 사격',
  'Technical Machine: Crisis Punch': '기술머신 위기펀치',
  'Technical Machine: Turbo Energize': '기술머신 에너지가속',
  'Therapeutic Energy': '세라피 에너지',
  'Vitality Band': '활력의 머리띠',
  Youngster: '반바지 어린이',
  'Arc Phone': '알세우스폰',
  'Aroma Lady': '아로마 레이디',
  'Aromatic Grass Energy': '아로마 풀 에너지',
  'Aurora Energy': '오로라 에너지',
  Avery: '세이버',
  'Ball Guy': '볼갱이',
  'Battle VIP Pass': '배틀 VIP 패스',
  'Big Charm': '큰 부적',
  'Big Parasol': '큰 파라솔',
  'Billowing Smoke': '자욱한 연기',
  'Bird Keeper': '새조련사',
  Blanche: '블랑쉐',
  'Blunder Policy': '실수보험',
  'Boost Shake': '부스트셰이크',
  'Box of Disaster': '재앙의 상자',
  Brandon: '진철',
  'Bug Catcher': '벌레잡이소년',
  'Burning Scarf': '스카프',
  'Café Master': '카페소믈리에',
  'Camping Gear': '캠핑 세트',
  'Canceling Cologne': '스위치코롱',
  Candela: '칸델라',
  'Capacious Bucket': '듬뿍양동이',
  'Cape of Toughness': '질긴의 망토',
  'Capture Energy': '캡처 에너지',
  'Capturing Aroma': '캡처아로마',
  'Chili & Cilan & Cress': '덴트·콩두·팟',
  Choy: '상인',
  'Circhester Bath': '키르쿠스타운 온천',
  'Cleansing Gloves': '정화의 글러브',
  'Coating Metal Energy': '코팅 강철 에너지',
  'Collapsed Stadium': '붕괴된 스타디움',
  'Cram-o-matic': '로봇우구우구',
  'Cross Switcher': '크로스 스위처',
  Crossceiver: '크로스 트랜시버',
  'Crushing Gloves': '분쇄의 글러브',
  'Crystal Cave': '결정 동굴',
  'Cursed Shovel': '저주의 삽',
  'Damage Pump': '데미지펌프',
  'Dark Patch': '다크패치',
  'Digging Duo': '구멍파기 형제',
  'Digging Gloves': '구멍파기 글러브',
  'Double Turbo Energy': '더블 터보 에너지',
  'Dream Ball': '드림볼',
  'Dyna Tree Hill': '다이나나무 언덕',
  'Earthen Seal Stone': '대지의 봉인석',
  'Echoing Horn': '메아리나팔',
  'Egg Incubator': '부화장치',
  'Elemental Badge': '엘리멘탈 뱃지',
  'Emergency Jelly': '비상용 젤리',
  'Energy Loto': '에너지 로토무',
  'Evolution Incense': '진화향로',
  'Expedition Uniform': '방한복',
  'Familiar Bell': '친숙한 방울',
  'Fan of Waves': '몰아치는 파도의 부채',
  'Farewell Bell': '작별의 종',
  'Feather Ball': '페더볼',
  'Fire-Resistant Gloves': '내화의 글러브',
  'Fog Crystal': '안개 수정',
  'Forest Seal Stone': '숲의 봉인석',
  'Fresh Water Set': '맛있는 물 세트',
  'Friends in Galar': '가라르의 친구들',
  'Friends in Hisui': '히스이의 친구들',
  'Friends in Sinnoh': '신오의 친구들',
  'Full Face Guard': '헬멧',
  'Furisode Girl': '후리소데',
  'Fusion Strike Energy': '퓨전 에너지',
  'Galar Mine': '가라르 광산',
  'Gapejaw Bog': '벌어진 턱 늪',
  'Gift Energy': '선물 에너지',
  'Glimwood Tangle': '아라베스크마을 체육관',
  Gloria: '방순이',
  Gordie: '마쿠와',
  'Gutsy Pickaxe': '배짱의 곡괭이',
  'Heat Fire Energy': '히트 불꽃 에너지',
  'Hiding Darkness Energy': '하이드 악 에너지',
  Honey: '밀벅',
  'Horror Psychic Energy': '호러 초 에너지',
  'Hunting Gloves': '사냥의 글러브',
  'Jubilife Village': '축복마을',
  'Justified Gloves': '정의의 글러브',
  Kabu: '순무',
  Klara: '도볼',
  'Lake Acuity': '예지호수',
  'Leafy Camo Poncho': '위장 폰초',
  'League Staff': '리그 스태프',
  'Lost City': '로스트시티',
  'Lost Vacuum': '로스트 스위퍼',
  'Lucky Egg': '행운의알',
  'Lucky Energy': '럭키 에너지',
  'Lucky Ice Pop': '행운의 아이스',
  'Lum Berry': '리샘열매',
  'Lure Module': '루어모듈',
  'Magma Basin': '마그마의 폭포',
  'Memory Capsule': '메모리 캡슐',
  'Metal Saucer': '금속소서',
  'Mirage Gate': '미라주게이트',
  'Miss Fortune Sisters': '세 자매',
  'Moomoo Cheese': '튼튼밀크 치즈',
  'Moon & Sun Badge': '태양과 달의 뱃지',
  Nugget: '금구슬',
  'Old Cemetery': '오래된 무덤',
  'Old PC': '옛날 PC',
  'Ordinary Rod': '보통 낚싯대',
  'Panic Mask': '패닉마스크',
  'Path to the Peak': '정상을 향한 눈길',
  'Poké Kid': '포켓몬키드',
  'PokéStop': '포켓스톱',
  'Pot Helmet': '냄비 헬멧',
  'Power Tablet': '파워탭',
  'Powerful Colorless Energy': '파워풀 무색 에너지',
  'Primordial Altar': '태고의 제단',
  'Professor Burnet': '버넷박사',
  'Professor Laventon': '라벤박사',
  'Quad Stone': '4개의 돌',
  'Rapid Strike Energy': '연격 에너지',
  'Rapid Strike Scroll of Swirls': '연격의 권이·소용돌이',
  'Rapid Strike Scroll of the Flying Dragon': '연격의 권이·비룡',
  'Rapid Strike Scroll of the Skies': '연격의 권이·천공',
  'Rapid Strike Style Mustard': '마스터 마스터 (연격)',
  'Rare Fossil': '드문 카세키',
  'Regenerative Energy': '리제네레이트 에너지',
  'Rescue Carrier': '구조캐리어',
  'Ribbon Badge': '리본 뱃지',
  Riley: '현이',
  'Rose Tower': '로즈타워',
  'Rubber Gloves': '고무 글러브',
  'Rugged Helmet': '고쯔고쯔메트',
  'Rusted Shield': '녹슨 방패',
  'Rusted Sword': '녹슨 검',
  'Scoop Up Net': '회수네트',
  'Shopping Center': '쇼핑센터',
  'Single Strike Scroll of Piercing': '일격의 권이·관통',
  'Single Strike Scroll of Scorn': '일격의 권이·분노',
  'Single Strike Scroll of the Fanged Dragon': '일격의 권이·용아',
  'Single Strike Style Mustard': '마스터 마스터 (일격)',
  'Sitrus Berry': '자뭉열매',
  'Sky Seal Stone': '하늘의 봉인석',
  'Snow Leaf Badge': '눈과 잎의 뱃지',
  'Sordward & Shielbert': '실디 & 소드',
  Spark: '스파크',
  'Speed Lightning Energy': '스피드 번개 에너지',
  'Spicy Seasoned Curry': '매운 맛 카레',
  Spikemuth: '스파이크마을',
  'Spiral Energy': '스파이럴 에너지',
  'Spirit Mask': '저주의 탈',
  'Spongy Gloves': '해면 글러브',
  'Stone Fighting Energy': '스톤 격투 에너지',
  'Stormy Mountains': '폭풍의 산맥',
  'Struggle Gloves': '투지의 글러브',
  'Supereffective Glasses': '약점보험 안경',
  'Suspicious Food Tin': '수상한 통조림',
  'Switch Cart': '교체카트',
  'Switching Cups': '교체 컵',
  'Team Yell Towel': '옐단 타올',
  'Telescopic Sight': '망원렌즈',
  'Temple of Sinnoh': '신오의 신전',
  Thorton: '주리',
  'Tool Box': '도구상자',
  'Tool Jammer': '툴 재머',
  'Tower of Darkness': '악의 탑',
  'Tower of Waters': '물의 탑',
  'Toy Catcher': '토이 캐처',
  'Training Court': '트레이닝 코트',
  'Treasure Energy': '보물 에너지',
  'Turbo Patch': '터보패치',
  'Turffield Stadium': '터프마을 체육관',
  'Twin Energy': '트윈 에너지',
  'Urn of Vitality': '활력의 항아리',
  'V Guard Energy': 'V 가드 에너지',
  'Wait and See Turbo': '살펴보기 터보',
  'Wash Water Energy': '워시 물 에너지',
  'Weeding Gloves': '제초 글러브',
  'Welcoming Lantern': '맞이하는 등불',
  'Windup Arm': '태엽 팔',
  'Wyndon Stadium': '슛스타디움',
  'Yell Horn': '옐단 나팔',
  'Adventure Bag': '모험의가방',
  'Aether Foundation Employee': '에테르재단 직원',
  'Aether Paradise Conservation Area': '에테르 파라다이스 보호구역',
  'Altar of the Moone': '월륜의 제단',
  'Altar of the Sunne': '일륜의 제단',
  'Ancient Crystal': '고대의 결정',
  'Apricorn Maker': '규토리 직공',
  'Aqua Patch': '아쿠아패치',
  'Beast Ball': '비스트볼',
  'Beast Bringer': '비스트 브링어',
  'Beast Energy ◇': '비스트 에너지 ◇',
  'Beast Ring': '비스트링',
  Beastite: '비스트나이트',
  'Bellelba & Brycen-Man': '애프터눈티',
  'Big Malasada': '큰 말라사다',
  'Bill\'s Analysis': '이수재의 분석',
  'Bill\'s Maintenance': '이수재의 메인터넌스',
  'Black Market ◇': '블랙마켓 ◇',
  'Blaine\'s Last Stand': '강철의 배수진',
  'Blaine\'s Quiz Show': '강철의 퀴즈',
  'Blizzard Town': '설화시티',
  'Blue\'s Tactics': '그린의 전략',
  'Bodybuilding Dumbbells': '머슬 아령',
  'Brock\'s Grit': '웅의 웅지',
  'Brock\'s Pewter City Gym': '웅의 회색시티 체육관',
  'Brock\'s Training': '웅의 단련',
  'Brooklet Hill': '잔물결영지',
  'Buff Padding': '바위 패딩',
  Channeler: '무당',
  'Chaotic Swell': '카오스스웰',
  'Cherish Ball': '프레셔스볼',
  'Chip-Chip Ice Axe': '단단한 얼음곡괭이',
  'Choice Helmet': '구애헬멧',
  'Coach Trainer': '코치 트레이너',
  'Counter Energy': '카운터 에너지',
  'Custom Catcher': '커스텀 캐처',
  'Cynthia & Caitlin': '난천 & 카틀레야',
  'Cyrus ◇': '태홍 ◇',
  'Damage Mover': '데미지스왑',
  Dana: '닥터',
  'Dangerous Drill': '데인저러스 드릴',
  'Dark City': '다크시티',
  'Dashing Pouch': '댓시 파우치',
  'Devolution Spray Z': '퇴화스프레이 Z',
  'Devoured Field': '약육강식의 들판',
  'Dragon Talon': '드래곤의 발톱',
  'Dragonium Z: Dragon Claw': '드래곤Z',
  'Draw Energy': '드로 에너지',
  'Dusk Stone': '어둠의돌',
  'Dust Island': '먼지섬',
  'Ear-Ringing Bell': '환각의 종',
  'Electric Memory': '전기 메모리',
  Electrocharger: '에렉키차저',
  'Electromagnetic Radar': '전자기 레이다',
  Electropower: '엘렉키파워',
  Eneporter: '에네포터',
  'Energy Recycle System': '에너지 회수 시스템',
  'Energy Spinner': '에너지 스피너',
  'Erika\'s Hospitality': '민화의 대접',
  'Escape Board': '탈출보드',
  Evelyn: '에블린',
  'Fairy Charm Ability': '페어리참 특성',
  'Fairy Charm Dragon': '페어리참 드래곤',
  'Fairy Charm Fighting': '페어리참 격투',
  'Fairy Charm Grass': '페어리참 풀',
  'Fairy Charm Lightning': '페어리참 번개',
  'Fairy Charm Psychic': '페어리참 초',
  'Fairy Charm UB': '페어리참 울트라비스트',
  'Fiery Flint': '불꽃 부싯돌',
  'Fighting Memory': '격투 메모리',
  'Fire Crystal': '불꽃 결정',
  'Fire Memory': '불꽃 메모리',
  'Flyinium Z: Air Slash': '비행Z',
  'Fossil Excavation Map': '카세키 발굴 지도',
  'Giant Bomb': '대형 폭탄',
  'Giant Hearth': '거대한 용광로',
  'Giovanni\'s Exile': '비주기의 추방',
  'Grass Memory': '풀 메모리',
  'Great Catcher': '그레이트 캐처',
  'Great Potion': '물약',
  'Green\'s Exploration': '불꽃의 탐구',
  'Guzma & Hala': '구즈마 & 할라',
  'Heat Factory ◇': '히트 공장 ◇',
  'Hustle Belt': '근성 머리띠',
  'Ingo & Emmet': '상행 & 상하',
  'Island Challenge Amulet': '아일랜드 챌린지 부적',
  'Jessie & James': '로사 & 로이',
  'Judge Whistle': '저지맨 호루라기',
  'Karate Belt': '가라테 띠',
  'Koga\'s Trap': '독수의 함정',
  'Lana\'s Fishing Rod': '수련의 낚싯대',
  'Lance ◇': '목호 ◇',
  'Last Chance Potion': '위기회복약',
  'Lavender Town': '보라타운',
  'Life Forest ◇': '생명의 숲 ◇',
  'Life Herb': '생명의 풀',
  Lisia: '루티아',
  Looker: '핸섬',
  'Looker Whistle': '핸섬 호루라기',
  'Lost Blender': '로스트 믹서',
  'Lt. Surge\'s Strategy': '마티스의 작전',
  'Lure Ball': '루어볼',
  'Lusamine ◇': '자몽 ◇',
  'Lysandre ◇': '플라드리 ◇',
  'Lysandre Labs': '플라드리 연구소',
  'Mallow & Lana': '마오 & 수련',
  'Martial Arts Dojo': '무도관 스타디움',
  'Memory Energy': '메모리 에너지',
  'Metal Core Barrier': '메탈코어 장벽',
  'Metal Frying Pan': '강철 프라이팬',
  'Metal Goggles': '메탈 고글',
  'Missing Clover': '행운의 클로버',
  'Misty & Lorelei': '이슬 & 칸나',
  'Mixed Herbs': '약초 혼합',
  Morgan: '모건',
  'Mount Lanakila': '라나키라마운틴',
  'Mt. Coronet': '천관산',
  'Multi Switch': '멀티 스위치',
  'Mysterious Treasure': '신비한 보물',
  Nita: '니타',
  'Normalium Z: Tackle': '노말Z',
  'Order Pad': '주문패드',
  'Peeking Red Card': '엿보기 레드카드',
  'Po Town': '포마을',
  'Poison Barb': '독침',
  'Pokémon Research Lab': '포켓몬 연구소',
  'Professor Elm\'s Lecture': '공박사의 가르침',
  'Professor Kukui': '쿠쿠이박사',
  'Professor Oak\'s Setup': '오박사의 세팅',
  'Psychic Memory': '초 메모리',
  'Rainbow Brush': '무지개 붓',
  'Recycle Energy': '리사이클 에너지',
  'Red & Blue': '레드 & 블루',
  'Red\'s Challenge': '레드의 도전',
  'Rescue Stretcher': '구조키트',
  'Reset Stamp': '리셋 스탬프',
  'Return Label': '반송 라벨',
  'Sabrina & Brycen': '초련 & 담죽',
  'Sabrina\'s Suggestion': '초련의 제안',
  'Samson Oak': '송호오',
  'Sea of Nothingness': '공허의 바다',
  'Shrine of Punishment': '응징의 사당',
  Sightseer: '관광객',
  'Sky Pillar': '하늘의 기둥',
  'Slumbering Forest': '수면의 숲',
  'Spell Tag': '저주의 부적',
  'Stadium Nav': '스타디움 네비',
  'Stealthy Hood': '은밀한 후드',
  'Super Boost Energy ◇': '슈퍼 부스트 에너지 ◇',
  'Super Scoop Up': '슈퍼회수',
  'Surprise Box': '깜짝 상자',
  'Switch Raft': '교체 뗏목',
  'Tag Call': '태그콜',
  'Tag Switch': '태그 스위치',
  'Tate & Liza': '풍 & 란',
  'Team Skull Grunt': '스컬단 조무래기',
  'The Masked Royal': '로열마스크',
  'Thunder Mountain ◇': '썬더 마운틴 ◇',
  'Tormenting Spray': '방해 스프레이',
  'Triple Acceleration Energy': '트리플 가속 에너지',
  'U-Turn Board': '유턴보드',
  'Ultra Space': '울트라스페이스',
  'Underground Expedition': '지하 탐험',
  'Unit Energy FightingDarknessFairy': '유닛 에너지 격투악페어리',
  'Unit Energy GrassFireWater': '유닛 에너지 풀불꽃물',
  'Unit Energy LightningPsychicMetal': '유닛 에너지 번개초강철',
  'Viridian Forest': '상록숲',
  'Wait and See Hammer': '살펴보기 해머',
  'Warp Energy': '워프 에너지',
  'Water Memory': '물 메모리',
  'Weakness Guard Energy': '약점 가드 에너지',
  'Weakness Policy': '약점보험',
  'Wela Volcano Park': '벨라 화산공원',
  Welder: '용접공',
  'Wishful Baton': '소원의 바통',
  'Wondrous Labyrinth ◇': '원더 라비린스 ◇',
  Zinnia: '피아나',
  'Ace Trainer': '엘리트 트레이너',
  'All-Night Party': '올나이트 파티',
  'Assault Vest': '돌격조끼',
  'Battle Compressor Team Flare Gear': '플레어단 기어 배틀압축기',
  'Battle Reporter': '배틀 리포터',
  'Bent Spoon': '구부러진 스푼',
  Blacksmith: '대장장이',
  Brigette: '이수진',
  'Buddy-Buddy Rescue': '친구친구 구조대',
  'Burning Energy': '버닝 에너지',
  'Bursting Balloon': '풍선 폭탄',
  'Captivating Poké Puff': '미혹의 포켓파플',
  Cassius: '칼름',
  'Chaos Tower': '카오스 타워',
  'Dangerous Energy': '데인저러스 에너지',
  'Devolution Spray': '퇴화스프레이',
  'Dimension Valley': '차원의 골짜기',
  'Double Dragon Energy': '더블 드래곤 에너지',
  'Eco Arm': '에코암',
  'Energy Pouch': '에너지 주머니',
  'Energy Reset': '에너지 리셋',
  Evosoda: '진화사이다',
  'Faded Town': '쇠퇴한 마을',
  'Fairy Drop': '페어리 드롭',
  'Fairy Garden': '페어리 가든',
  'Fiery Torch': '단단한 횃불',
  'Fighting Fury Belt': '투혼의 띠',
  'Fighting Stadium': '격투 도장',
  'Flash Energy': '플래시 에너지',
  'Float Stone': '가벼운돌',
  'Forest of Giant Plants': '거대식물의 숲',
  'Fossil Excavation Kit': '카세키 발굴 키트',
  'Fossil Researcher': '카세키 연구원',
  'Greedy Dice': '욕심쟁이 주사위',
  'Hand Scope': '핸드스코프',
  'Hard Charm': '단단한 부적',
  'Head Ringer Team Flare Hyper Gear': '플레어단 하이퍼기어 헤드링어',
  'Healing Scarf': '치료 머플러',
  'Heavy Boots': '헤비 부츠',
  'Herbal Energy': '허브 에너지',
  'Here Comes Team Rocket!': '로켓단이 온다!',
  'Hex Maniac': '오컬트 마니아',
  'Jamming Net Team Flare Hyper Gear': '플레어단 하이퍼기어 재밍넷',
  'Jaw Fossil': '턱카세키',
  'Magnetic Storm': '자기장 폭풍',
  'Max Elixir': '맥스 엘릭서',
  'Max Revive': '기력의 덩어리',
  'Mountain Ring': '산맥 링',
  'Mystery Energy': '미스터리 에너지',
  'Ninja Boy': '닌자소년',
  'Paint Roller': '페인트 롤러',
  'Parallel City': '파라렐 시티',
  'Pokémon Ranger': '포켓몬 레인저',
  'Power Memory': '파워 메모리',
  'Protection Cube': '프로텍트 큐브',
  'Puzzle of Time': '시간의 파즐',
  'Random Receiver': '랜덤수신기',
  'Red Card': '레드카드',
  'Repeat Ball': '리피트볼',
  'Reserved Ticket': '예매권',
  'Reverse Valley': '리버스 골짜기',
  'Robo Substitute Team Flare Gear': '플레어단 기어 로봇대타출동',
  'Rough Seas': '거친 바다',
  'Sail Fossil': '지느러미카세키',
  'Scorched Earth': '타오르는 들판',
  'Shadow Circle': '섀도 서클',
  'Shield Energy': '실드 에너지',
  'Shrine of Memories': '추억의 사당',
  'Silent Lab': '무음의 연구소',
  'Sky Field': '스카이필드',
  'Sparkling Robe': '반짝이는 로브',
  'Special Charge': '스페셜 차치',
  'Splash Energy': '스플래시 에너지',
  'Startling Megaphone': '메가폰',
  'Steel Shelter': '스틸 셸터',
  'Strong Energy': '스트롱 에너지',
  'Target Whistle Team Flare Gear': '플레어단 기어 타깃 호루라기',
  Teammates: '탑승 파트너',
  'Tool Retriever': '도구 회수',
  'Town Map': '타운맵',
  'Trainers\' Mail': '트레이너스 우체통',
  'Training Center': '트레이닝 센터',
  Trevor: '트로바',
  'Trick Coin': '트릭 코인',
  'Trick Shovel': '트릭 삽',
  'VS Seeker': '배틀서처',
  'Wide Lens': '와이드렌즈',
  'Wonder Energy': '원더 에너지',
  'Aspertia City Gym': '부채시티 체육관',
  'Battle City': '배틀시티',
  'Blend Energy Grass Fire Psychic Darkness': '혼합 에너지 풀불꽃초악',
  'Blend Energy Water Lightning Fighting Metal': '혼합 에너지 물번개격투강철',
  'Cedric Juniper': '주박사',
  'Colress Machine': '아크로마 머신',
  'Cover Fossil': '덮개카세키',
  'Crystal Edge': '크리스탈 엣지',
  'Crystal Wall': '크리스탈 월',
  'Dark Claw': '다크 클로',
  Ether: '에테르',
  Eviolite: '진화의돌',
  'Frozen City': '얼어붙은 도시',
  'G Booster': 'G 부스터',
  'G Scope': 'G 스코프',
  'Giant Cape': '거대한 망토',
  'Gold Potion': '골드 포션',
  'Hooligans Jim & Cas': '갱단',
  Hugh: '휴',
  'Hypnotoxic Laser': '독가스 레이저',
  'Life Dew': '생명의 이슬',
  'Plasma Energy': '플라스마 에너지',
  'Plasma Frigate': '플라스마 프리깃함',
  'Plume Fossil': '깃털카세키',
  'Pokémon Center': '포켓몬센터',
  Recycle: '리사이클',
  'Rescue Scarf': '구조 머플러',
  'Reversal Trigger': '리버스 트리거',
  'Rock Guard': '로크 가드',
  'Shadow Triad': '다크트리니티',
  'Silver Bangle': '실버 뱅글',
  'Silver Mirror': '실버 미러',
  'Skyarrow Bridge': '스카이아로 브리지',
  'Team Plasma Badge': '플라스마단 뱃지',
  'Team Plasma Ball': '플라스마단 볼',
  'Team Plasma Grunt': '플라스마단 조무래기',
  'Tropical Beach': '트로피컬 비치',
  'Twist Mountain': '태엽산',
  'Victory Cup': '비토리컵',
  'Victory Piece': '비토리 피스',
  'Virbank City Gym': '모란만시티 체육관',
  Xtransceiver: '라이브캐스터',
  'Alph Lithograph': '알프의 유적',
  'Amulet Coin': '부적금화',
  'Ancient Technical Machine (Ice)': '고대 기술머신 (얼음)',
  'Ancient Technical Machine (Rock)': '고대 기술머신 (바위)',
  'Ancient Technical Machine (Steel)': '고대 기술머신 (강철)',
  'Armor Fossil': '발톱카세키',
  'Balloon Berry': '풍선 열매',
  'Battle Frontier': '배틀프런티어',
  'Battle Tower': '배틀타워',
  'Bench Shield': '벤치 실드',
  Berry: '나무열매',
  Bill: '이수재',
  'Black Belt': '태권왕',
  'Broken Time-Space': '시공의 왜곡',
  'Call Energy': '콜 에너지',
  Castaway: '조난자',
  'Cessation Crystal': '봉인의 결정',
  'Computer Error': '컴퓨터 오류',
  'Curse Powder': '저주의 가루',
  'Cyclone Energy': '사이클론 에너지',
  'Dark Metal Energy': '다크 메탈 에너지',
  Dawn: '빛나',
  'Dawn Stadium': '여명의 스타디움',
  'Desert Ruins': '사막의 유적',
  Digger: '구멍파기',
  'Dome Fossil': '껍질카세키',
  'Dual Ball': '듀얼볼',
  'Energy Amplifier': '에너지 증폭기',
  'Energy Charge': '에너지 차치',
  'Energy Removal 2': '에너지 전송 2',
  'Energy Stadium': '에너지 스타디움',
  'Fast Ball': '스피드볼',
  Fossil: '카세키',
  Gambler: '도박사',
  'Gold Berry': '황금 열매',
  'Good Rod': '좋은 낚싯대',
  'Heal Energy': '치료 에너지',
  'Heal Powder': '치료 가루',
  'Helix Fossil': '조개카세키',
  'Holon Energy FF': '홀론 에너지 FF',
  'Holon Energy GL': '홀론 에너지 GL',
  'Holon Energy WP': '홀론 에너지 WP',
  'Holon Mentor': '홀론의 스승',
  'Junk Arm': '정크암',
  'Lady Outing': '아가씨',
  Lass: '미니스커트',
  'Legend Box': '레전드 박스',
  'Light Ball': '전기구슬',
  'Lucky Stadium': '행운의 스타디움',
  'Miracle Berry': '기적의 열매',
  'Miracle Energy': '기적의 에너지',
  'Mr. Briney\'s Compassion': '하구의 배려',
  'Mr. Fuji': '등나무 노인',
  'Mt. Moon': '달맞이산',
  'Old Rod': '낡은 낚싯대',
  'Oran Berry': '오랭열매',
  'Pewter City Gym': '회색시티 체육관',
  'Poké Radar': '포켓몬 포레',
  'PokéGear': '포켓기어',
  'Pokémon Collector': '포켓몬 컬렉터',
  'Pokémon Flute': '포켓몬의 피리',
  'Pokémon Nurse': '포켓몬 간호사',
  'Pokémon Trader': '포켓몬 교환 아저씨',
  'Power Charge': '파워 차치',
  'Premier Ball': '프레미어볼',
  'Professor Birch': '털보박사',
  'Professor Elm': '공박사',
  'Professor Oak': '오박사',
  'Professor Rowan': '마박사',
  'Professor\'s Letter': '박사의 편지',
  'Rescue Energy': '리스큐 에너지',
  'Resistance Gym': '저항 체육관',
  Revitalizer: '회복약',
  'Roseanne\'s Research': '이슬의 조사',
  'Scramble Energy': '스크램블 에너지',
  'Secret Mission': '비밀 미션',
  'Scoop Up': '포켓몬 회수',
  'Skull Fossil': '두개골카세키',
  'Super Energy Removal': '슈퍼 에너지 제거',
  'Team Galactic Grunt': '갤럭시단 조무래기',
  'Team Rocket': '로켓단',
  'Time Capsule': '타임캡슐',
  'Town Volunteers': '마을의 봉사자',
  Windstorm: '폭풍',
  // ── 사용자가 확인해 준 공식 한글 카드명(2026-07-26) ──────────────────────
  // 애매했던 것들도 사용자가 하나로 특정해 줬다(2026-07-26).
  // Cyrano는 블루베리 아카데미 이사장으로 Clavell(클라벨)과 다른 인물이다.
  Cyrano: '시아노',
  'Heat Rotom': '히트 로토무',
  'Buddy-Buddy Poffin': '페포마을포핀',
  "Daisy's Help": '나나미의 도와주기',
  'Grand Tree': '그랜드 트리',
  "Hop's Choice Band": '호프의 구애머리띠',
  "Team Rocket's Transceiver": '로켓단의 송수신기',
  // 이름 전체가 정확히 일치할 때만 바뀌므로 다른 카드를 깨뜨리지 않는다.
  'Accompanying Flute': '동반의 피리',
  "Acerola's Mischief": '아세로라의 장난',
  Amarys: '네리네',
  'Amulet of Hope': '희망의 부적',
  'Antique Cover Fossil': '복원된 덮개화석',
  'Antique Dome Fossil': '복원된 껍질화석',
  'Antique Helix Fossil': '복원된 조개화석',
  'Antique Old Amber': '복원된 비밀의암석',
  'Antique Root Fossil': '복원된 뿌리화석',
  'Area Zero Underdepths': '제로대공동',
  Artazon: '보울마을',
  "Arven's Sandwich": '페퍼의 샌드위치',
  'Babiri Berry': '바카열매',
  'Big Air Balloon': '커다란 풍선',
  "Bill's Transfer": '이수재의 전송',
  "Billy & O'Nare": '브라이어 & 오네어',
  'Binding Mochi': '사슬떡',
  "Black Belt's Training": '태권왕의 특훈',
  'Black Kyurem ex': '블랙큐레무 ex',
  'Bloodmoon Ursaluna': '다투곰 붉은 달',
  'Bloodmoon Ursaluna ex': '다투곰 붉은 달 ex',
  'Boomerang Energy': '부메랑 에너지',
  'Bravery Charm': '용기의 부적',
  'Brilliant Blender': '브릴리언트 블렌더',
  'Bug Catching Set': '곤충채집 세트',
  'Call Bell': '호출벨',
  Caretaker: '안내인',
  Carmine: '카민',
  'Castform Sunny Form': '캐스퐁 태양의 모습',
  'Chill Teaser Toy': '차가운 장난감',
  "Ciphermaniac's Codebreaking": '암호마니아의 해독',
  "Clemont's Quick Wit": '시트론의 재치',
  'Colbur Berry': '마코열매',
  'Community Center': '공통 센터',
  'Cornerstone Mask Ogerpon': '주징의 가면 오거폰',
  'Cornerstone Mask Ogerpon ex': '주징의 가면 오거폰 ex',
  'Counter Gain': '카운터 게인',
  'Cycling Road': '사이클링 로드',
  "Cynthia's Power Weight": '난천의 파워웨이트',
  'Deduction Kit': '추리키트',
  'Deluxe Bomb': '디럭스 폭탄',
  'Dragon Elixir': '드래곤 에릭서',
  'Dusk Ball': '다크볼',
  'Earthen Vessel': '대지의 용기',
  "Emcee's Hype": '사회자의 사회',
  'Energy Search Pro': '에너지 수색 프로',
  'Energy Sticker': '에너지 스티커',
  'Enriching Energy': '풍요의 에너지',
  "Erika's Invitation": '민화의 초대',
  "Ethan's Adventure": '심향의 모험',
  "Explorer's Guidance": '탐험가의 안내',
  'Fan Rotom': '스핀 로토무',
  'Festival Grounds': '축제 광장',
  'Fighting Gong': '격투 징',
  'Friends in Paldea': '팔데아의 친구들',
  "Giovanni's Charisma": '비주기의 카리스마',
  'Glass Trumpet': '유리 나팔',
  Grabber: '핸드캐처',
  'Granite Cave': '바위동굴',
  'Gravity Gemstone': '중력의 보석',
  'Gravity Mountain': '중력 산',
  'Haban Berry': '야느와르열매',
  'Handheld Fan': '핸디 팬',
  'Hearthflame Mask Ogerpon': '화덕의 가면 오거폰',
  'Hearthflame Mask Ogerpon ex': '화덕의 가면 오거폰 ex',
  "Hop's Bag": '호프의 가방',
  'Hyper Aroma': '하이퍼 아로마',
  "Iris's Fighting Spirit": '아이리스의 투지',
  'Iron Defender': '무쇠 방어구',
  'Jamming Tower': '방해 타워',
  "Janine's Secret Art": '도희의 비술',
  "Jasmine's Gaze": '규리의 시선',
  'Jet Energy': '제트 에너지',
  Lacey: '타로',
  "Lana's Aid": '수련의 지원',
  "Larry's Skill": '청목의 요령',
  Leftovers: '먹고자남은음식',
  'Legacy Energy': '레거시 에너지',
  'Letter of Encouragement': '응원 편지',
  "Lillie's Determination": '릴리에의 결의',
  "Lillie's Pearl": '릴리에의 진주',
  "Lisia's Appeal": '루치아의 어필',
  'Lively Stadium': '활기찬 스타디움',
  'Love Ball': '러브러브볼',
  "Lt. Surge's Bargain": '마티스의 거래',
  'Lucky Helmet': '행운의 헬멧',
  'Luminous Energy': '루미너스 에너지',
  'Max Rod': '맥스 낚싯대',
  'Maximum Belt': '맥시멈 벨트',
  'Meddling Memo': '참견 메모',
  'Mega Signal': '메가 시그널',
  'Megaton Blower': '메가톤 블로어',
  'Miracle Headset': '미라클 헤드셋',
  'Mow Rotom': '커트 로토무',
  'Mystery Garden': '신비의 정원',
  "N's Castle": 'N의 성',
  "N's PP Up": 'N의 포인트업',
  'Night Stretcher': '야간 들것',
  'Occa Berry': '바쿨열매',
  "Ogre's Mask": '오거의 가면',
  'Passho Berry': '어름열매',
  'Patrol Cap': '순찰모자',
  'Payapa Berry': '바나열매',
  'Pokémon League Headquarters': '포켓몬리그 본부',
  Postwick: '펄롱마을',
  'Precious Trolley': '프레셔스 카트',
  'Premium Power Pro': '프리미엄 파워 프로',
  'Prime Catcher': '프라임 캐처',
  "Professor Sada's Vitality": '올림박사의 기력',
  "Professor Turo's Scenario": '투로박사의 시나리오',
  'Protective Goggles': '방진고글',
  Raifort: '레포르',
  'Redeemable Ticket': '상환 티켓',
  Repel: '벌레퇴치스프레이',
  'Rescue Board': '구조 보드',
  'Rigid Band': '단단한 밴드',
  'Risky Ruins': '위험한 유적',
  'Roto-Stick': '로토무 셀카봉',
  Ruffian: '불량배',
  'Sacred Ash': '성스러운재',
  'Scoop Up Cyclone': '회수 사이클론',
  'Scramble Switch': '스크램블 교체',
  'Secret Box': '시크릿 박스',
  'Sparkling Crystal': '반짝이는 결정',
  'Spikemuth Gym': '스파이크마을 체육관',
  'Spiky Energy': '가시 에너지',
  'Strange Timepiece': '이상한 시계',
  Surfer: '서퍼',
  'Surfing Beach': '파도타기 해변',
  'Survival Brace': '서바이벌 깁스',
  'TM Machine': '기술머신 머신',
  'Teal Mask Ogerpon': '벽록의 가면 오거폰',
  'Teal Mask Ogerpon ex': '벽록의 가면 오거폰 ex',
  "Team Rocket's Archer": '로켓단의 아폴로',
  "Team Rocket's Ariana": '로켓단의 아테나',
  "Team Rocket's Bother-Bot": '로켓단의 방해 로봇',
  "Team Rocket's Energy": '로켓단의 에너지',
  "Team Rocket's Factory": '로켓단의 공장',
  "Team Rocket's Giovanni": '로켓단의 비주기',
  "Team Rocket's Great Ball": '로켓단의 수퍼볼',
  "Team Rocket's Petrel": '로켓단의 람다',
  "Team Rocket's Proton": '로켓단의 랜스',
  "Team Rocket's Venture Bomb": '로켓단의 벤처 폭탄',
  "Team Rocket's Watchtower": '로켓단의 감시탑',
  'Team Star Grunt': '스타단 조무래기',
  'Technical Machine: Fluorite': '기술머신 플로라이트',
  'Techno Radar': '테크노 레이더',
  'Tera Orb': '테라스탈 오브',
  'Town Store': '마을 상점',
  'Treasure Tracker': '보물 추적기',
  Tyme: '타임',
  'Unfair Stamp': '언페어 스탬프',
  'Vengeful Punch': '보복의 펀치',
  "Wally's Compassion": '민진의 자비',
  'Wash Rotom': '워시 로토무',
  'Wellspring Mask Ogerpon': '우물질의 가면 오거폰',
  'Wellspring Mask Ogerpon ex': '우물질의 가면 오거폰 ex',
  // 회복 아이템
  Potion: '상처약',
  'Super Potion': '좋은상처약',
  'Hyper Potion': '뛰어난상처약',
  'Max Potion': '최고상처약',
  'Full Heal': '만능제',
  // 볼
  'Poké Ball': '몬스터볼',
  'Great Ball': '슈퍼볼',
  'Ultra Ball': '하이퍼볼',
  'Master Ball': '마스터볼',
  'Quick Ball': '퀵볼',
  'Nest Ball': '네스트볼',
  'Net Ball': '넷볼',
  'Dive Ball': '다이브볼',
  'Level Ball': '레벨볼',
  'Luxury Ball': '럭셔리볼',
  'Timer Ball': '타이머볼',
  'Heavy Ball': '헤비볼',
  'Friend Ball': '프렌드볼',
  // 도구·기기
  'Rare Candy': '이상한사탕',
  Switch: '포켓몬 교체',
  PlusPower: '플러스파워',
  Defender: '디펜더',
  Pokédex: '포켓몬도감',
  'Pokégear 3.0': '포켓기어3.0',
  PokéNav: '포켓내비',
  'Pal Pad': '팔패드',
  'Super Rod': '슈퍼로드',
  'Air Balloon': '풍선',
  'Rocky Helmet': '울퉁불퉁멧', // 공식 카드 SV1V 073으로 확인
  'Pokémon Catcher': '포켓몬 캐처',
  'Crushing Hammer': '크래시해머',
  'Enhanced Hammer': '강화해머',
  'Tool Scrapper': '툴스크래퍼',
  'Field Blower': '필드블로어',
  'Trekking Shoes': '트레킹슈즈',
  'Strength Charm': '힘의 부적',
  'Escape Rope': '탈출용밧줄',
  'Warp Point': '워프포인트',
  'Energy Switch': '에너지 전환',
  'Energy Search': '에너지 서치',
  'Energy Retrieval': '에너지 회수',
  'Energy Recycler': '에너지 리사이클',
  'Energy Removal': '에너지 제거',
  Copycat: '카피캣',
  'Gym Badge': '체육관 배지',
  'Champions Festival': '챔피언스 페스티벌',
  'Pokémon Communication': '포켓몬 교환',
  'Quick Search': '퀵서치',
  // 에너지
  'Water Energy': '물 에너지',
  'Fire Energy': '불꽃 에너지',
  'Grass Energy': '풀 에너지',
  'Lightning Energy': '번개 에너지',
  'Psychic Energy': '초 에너지',
  'Fighting Energy': '격투 에너지',
  'Darkness Energy': '악 에너지',
  'Metal Energy': '강철 에너지',
  'Fairy Energy': '페어리 에너지',
  'Dragon Energy': '드래곤 에너지',
  'Rainbow Energy': '무지개 에너지',
  'Multi Energy': '멀티 에너지',
  'Double Colorless Energy': '더블무색 에너지',
  'Double Rainbow Energy': '더블무지개 에너지',
  'Boost Energy': '부스트 에너지',
  'Basic Water Energy': '기본 물 에너지',
  'Basic Fire Energy': '기본 불꽃 에너지',
  'Basic Grass Energy': '기본 풀 에너지',
  'Basic Lightning Energy': '기본 번개 에너지',
  'Basic Psychic Energy': '기본 초 에너지',
  'Basic Fighting Energy': '기본 격투 에너지',
  'Basic Darkness Energy': '기본 악 에너지',
  'Basic Metal Energy': '기본 강철 에너지',
  // 화석
  'Mysterious Fossil': '신비의 화석',
  'Unidentified Fossil': '정체불명의 화석',
  'Root Fossil': '뿌리화석',
  'Claw Fossil': '발톱화석',
  'Old Amber': '비밀의 호박',
  // 일반 역할 인물
  Fisherman: '낚시꾼',
  Lady: '귀부인',
  Beauty: '미인',
  Schoolboy: '남학생',
  Schoolgirl: '여학생',
  'TV Reporter': 'TV 리포터',
  'Gym Trainer': '체육관 트레이너',
  'Pokémon Fan Club': '포켓몬 팬클럽',
  'Pokémon Center Lady': '포켓몬센터 누나',
  Maintenance: '메인터넌스',
  'Night Maintenance': '나이트 메인터넌스',
  Revive: '기력의 조각',
  // 일본판 경로는 이미 '저지맨'인데 영문판만 '심판꾼'이었다(사용자 지적).
  Judge: '저지맨',
  'Choice Band': '구애머리띠',
  'Power Plant': '발전소',
  'Computer Search': '컴퓨터 서치',
  // 일반 역할 인물 추가
  Worker: '인부',
  Cook: '요리사',
  Dancer: '댄서',
  Doctor: '의사',
  Delinquent: '불량소녀',
  Kindler: '불꽃술사',
};

// PokemonPriceTracker는 일본판 DB도 TCGPlayer 영문 표기로 내려준다("Charizard ex").
// SNKRDUNK 쪽 koreanizeTitle이 일본어 전용이라 여기엔 못 쓰므로, 영문 카드명을
// 한글 포켓몬 이름으로 치환하는 별도 경로를 둔다.
// 검색용 역방향 사전(한글 → 영문). 위 두 표는 "영문 카드명 → 한글"이라 화면 표시에만
// 쓰였고, 한글로 검색하면 영문 시세(eBay·TCGplayer)에서 아무것도 안 나왔다.
// ⚠️ 2글자 이하 이름(추명·이슬·모란 …)은 다른 말에 끼어들어 검색을 깨뜨리므로,
//    통째로 일치할 때만 쓰고 부분 치환에는 3글자 이상만 넣는다.
const koToEnEntries: [string, string][] = Object.entries({ ...TRAINER_EN_TO_KO, ...ITEM_EN_TO_KO }).map(([en, ko]) => [ko, en]);
export const CARD_NAME_KO_TO_EN = new Map<string, string>(koToEnEntries);
export const CARD_NAME_KO_TO_EN_LONG: [string, string][] = koToEnEntries
  .filter(([ko]) => ko.replace(/\s/g, '').length >= 3)
  .sort((a, b) => b[0].length - a[0].length);

// 대소문자를 무시하되 앞뒤가 알파벳이면 건너뛴다. 그냥 대소문자만 풀면
// "Aaron's Collection"의 aron이 가보리(Aron)로 잡혀 "A가보리's"가 된다.
const pokemonEnPatterns = sortedPokemonEnKo.map((entry) => ({
  re: new RegExp(`(?<![A-Za-z])${entry.en.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}(?![A-Za-z])`, 'gi'),
  ko: entry.ko,
}));

export function koreanizeEnglishCardName(name: string): string {
  // 트레이너·인물·아이템 카드는 이름 전체가 일치할 때만 통째로 바꾼다(부분 치환 사고 방지).
  // 데이터마다 어포스트로피가 곧은(') / 굽은(’) 게 섞여 있어, 사전 키(곧은 ')에 맞게
  // 굽은 것을 곧은 것으로 바꿔 조회한다.
  const exactKey = name.trim().replace(/[’]/g, "'");
  const exact = TRAINER_EN_TO_KO[exactKey] ?? ITEM_EN_TO_KO[exactKey];
  if (exact) return exact;

  // PokemonPriceTracker는 "Levincia - 092/063"처럼 이름 뒤에 카드 번호를 붙여 준다.
  // 번호를 뗀 뒤 찾고, 번호는 그대로 뒤에 다시 붙인다(안 그러면 영문 그대로 남는다).
  const numbered = exactKey.match(/^(.+?)\s+-\s+([A-Za-z0-9/-]+)$/);
  if (numbered) {
    const found = TRAINER_EN_TO_KO[numbered[1]] ?? ITEM_EN_TO_KO[numbered[1]];
    if (found) return `${found} - ${numbered[2]}`;
  }
  // "Judge (Mirror Holo)"처럼 괄호로 인쇄 방식이 붙는 것도 같은 방식으로 처리한다.
  const suffixed = exactKey.match(/^(.+?)\s+(\([^()]+\))$/);
  if (suffixed) {
    const found = TRAINER_EN_TO_KO[suffixed[1]] ?? ITEM_EN_TO_KO[suffixed[1]];
    if (found) return `${found} ${suffixed[2]}`;
  }

  // 북미판 세트인데 원본 DB가 "ナッシー[Exeggutor]"처럼 일본어 이름에 영어 이름을
  // 대괄호로 덧붙여 둔 경우가 있다. 대괄호 안이 진짜 이름이라 그것만 남긴다.
  const bracketed = name.trim().match(/^[ァ-ヶー・]+\[(.+)\]$/);
  const base = bracketed ? bracketed[1] : name;

  let result = base;
  // 표기 차이 보정: 카드 데이터는 곧은 어포스트로피(Farfetch'd)와 성별 기호 앞 공백
  // (Nidoran ♂)을 쓰는데, 사전은 굽은 어포스트로피(Farfetch’d)·붙임(Nidoran♂) 표기라
  // 그대로는 파오리·니드런이 안 잡힌다. 사전 표기에 맞춰 정규화한다.
  result = result.replace(/'/g, '’').replace(/\s+([♂♀])/g, '$1');

  for (const [en, ko] of STRUCTURAL_EN_TO_KO) {
    if (result.includes(en)) {
      result = result.split(en).join(ko);
    }
  }
  // 세트에 따라 "slowpoke"·"REMORAID"처럼 대소문자가 제각각이라, 대소문자를 무시하고 맞춘다.
  for (const entry of pokemonEnPatterns) {
    entry.re.lastIndex = 0;
    if (entry.re.test(result)) {
      entry.re.lastIndex = 0;
      result = result.replace(entry.re, entry.ko);
    }
  }

  return result;
}

// 일본판 세트명은 "SV4a: Shiny Treasure ex"처럼 팩 코드가 앞에 붙어 오므로, 그 코드로
// 한글 팩 이름을 찾는다. 북미판 세트("Obsidian Flames" 등)는 코드가 없어 원문을 유지한다.
export function koreanizeEnglishSetName(setName: string): string {
  const match = setName.match(/^([A-Za-z0-9-]+):\s*/);
  if (!match) return setName;
  return packKoByCode.get(match[1].toLowerCase()) ?? setName;
}
