// 북미판·Pocket 세트의 공식 한글명(영어명 그대로면 한글 사이트에서 어색).
// 키는 영어 세트명 — 원본 name은 그대로 둬서 영어 검색도 계속 되게 한다.
// 세트별 목록(SetsView)과 작가별 목록(ArtistsView)이 같은 세트를 같은 한글명으로
// 보여줘야 해서 공용 모듈로 뒀다. 두 화면 모두 지연 로딩이라 컴포넌트끼리 import하면
// 코드 분리가 깨지므로 lib에 둔다.
export const SET_KO: Record<string, string> = {
  // Pokémon TCG Pocket (한국어판 게임 공식 확장팩명, 나무위키 대조)
  'Genetic Apex': '최강의 유전자',
  'Mythical Island': '환상이 있는 섬',
  'Space-Time Smackdown': '시공의 격투',
  'Triumphant Light': '초극의 빛',
  'Shining Revelry': '샤이닝 하이',
  'Celestial Guardians': '쌍천의 수호자',
  'Extradimensional Crisis': '이차원 크라이시스',
  'Eevee Grove': '이브이 가든',
  'Wisdom of Sea and Sky': '하늘과 바다의 인도',
  'Secluded Springs': '미지의 수역',
  'Mega Rising': '메가라이징',
  'Crimson Blaze': '홍련 블레이즈',
  'Fantastical Parade': '몽환 퍼레이드',
  'Promos-A': '프로모 카드 A',

  // ── 물리 북미판(EN) ──
  // 일본판 1개와 1:1 대응하는 세트는 정식 한글명, 합본·북미전용은 음역(사용자 선택 A).
  // Mega Evolution (EN 메가 시리즈)
  'Mega Evolution': '메가 에볼루션',
  'Phantasmal Flames': '팬타스말 플레임즈',
  'Ascended Heroes': '어센디드 히어로즈',
  'Perfect Order': '퍼펙트 오더',
  'Chaos Rising': '카오스 라이징',
  'Pitch Black': '피치 블랙',
  // Scarlet & Violet
  'Scarlet & Violet': '스칼렛 & 바이올렛',
  'Paldea Evolved': '팔데아 이볼브드',
  'Obsidian Flames': '흑염의 지배자',
  '151': '포켓몬 카드 151',
  'Paradox Rift': '패러독스 리프트',
  'Paldean Fates': '샤이니트레저 ex',
  'Temporal Forces': '템포럴 포스',
  'Twilight Masquerade': '변환의 가면',
  'Shrouded Fable': '나이트원더러',
  'Stellar Crown': '스텔라미라클',
  'Surging Sparks': '초전브레이커',
  'Prismatic Evolutions': '테라스탈 페스타 ex',
  'Journey Together': '배틀파트너즈',
  'Destined Rivals': '데스틴드 라이벌즈',
  'Black Bolt': '블랙볼트',
  'White Flare': '화이트플레어',
  'SVP Black Star Promos': 'SVP 블랙스타 프로모',
  // Sword & Shield
  'Sword & Shield': '소드 & 실드',
  'Rebel Clash': '리벨 클래시',
  'Darkness Ablaze': '다크니스 어블레이즈',
  "Champion's Path": '챔피언스 패스',
  'Vivid Voltage': '비비드 볼티지',
  'Shining Fates': '샤이닝 페이츠',
  'Shining Fates Shiny Vault': '샤이닝 페이츠 샤이니 볼트',
  'Battle Styles': '배틀 스타일즈',
  'Chilling Reign': '칠링 레인',
  'Evolving Skies': '이볼빙 스카이즈',
  'Celebrations': '셀레브레이션즈',
  'Fusion Strike': '퓨전 스트라이크',
  'Brilliant Stars': '브릴리언트 스타즈',
  'Brilliant Stars Trainer Gallery': '브릴리언트 스타즈 트레이너 갤러리',
  'Astral Radiance': '아스트랄 라디언스',
  'Astral Radiance Trainer Gallery': '아스트랄 라디언스 트레이너 갤러리',
  'Pokémon GO': '포켓몬 GO',
  'Lost Origin': '로스트 오리진',
  'Lost Origin Trainer Gallery': '로스트 오리진 트레이너 갤러리',
  'Silver Tempest': '실버 템페스트',
  'Silver Tempest Trainer Gallery': '실버 템페스트 트레이너 갤러리',
  'Crown Zenith': '크라운 제니스',
  'Crown Zenith Galarian Gallery': '크라운 제니스 가라르 갤러리',
  'Pokémon Futsal 2020': '포켓몬 풋살 2020',
  'SWSH Black Star Promos': 'SWSH 블랙스타 프로모',
  // Sun & Moon
  'Sun & Moon': '썬 & 문',
  'Guardians Rising': '가디언즈 라이징',
  'Burning Shadows': '버닝 섀도우',
  'Shining Legends': '샤이닝 레전드',
  'Crimson Invasion': '크림슨 인베이전',
  'Ultra Prism': '울트라 프리즘',
  'Forbidden Light': '포비든 라이트',
  'Celestial Storm': '셀레스티얼 스톰',
  'Dragon Majesty': '드래곤 마제스티',
  'Lost Thunder': '로스트 썬더',
  'Team Up': '팀 업',
  'Detective Pikachu': '명탐정 피카츄',
  'Unbroken Bonds': '언브로큰 본즈',
  'Unified Minds': '유나이티드 마인드',
  'Hidden Fates': '히든 페이츠',
  'Hidden Fates Shiny Vault': '히든 페이츠 샤이니 볼트',
  'Cosmic Eclipse': '코스믹 이클립스',
  'SM Black Star Promos': 'SM 블랙스타 프로모',
  // XY
  'XY': 'XY',
  'Kalos Starter Set': '칼로스 스타터 세트',
  'Flashfire': '플래시파이어',
  'Furious Fists': '퓨리어스 피스트',
  'Phantom Forces': '팬텀 포스',
  'Primal Clash': '프라이멀 클래시',
  'Double Crisis': '더블 크라이시스',
  'Roaring Skies': '로어링 스카이즈',
  'Ancient Origins': '에인션트 오리진',
  'BREAKthrough': '브레이크스루',
  'BREAKpoint': '브레이크포인트',
  'Generations': '제너레이션즈',
  'Fates Collide': '페이츠 콜라이드',
  'Steam Siege': '스팀 시즈',
  'Evolutions': '이볼루션즈',
  'XY Black Star Promos': 'XY 블랙스타 프로모',
  // Black & White
  'Black & White': '블랙 & 화이트',
  'Emerging Powers': '이머징 파워',
  'Noble Victories': '노블 빅토리',
  'Next Destinies': '넥스트 데스티니',
  'Dark Explorers': '다크 익스플로러',
  'Dragons Exalted': '드래곤즈 이그절티드',
  'Dragon Vault': '드래곤 볼트',
  'Boundaries Crossed': '바운더리즈 크로스드',
  'Plasma Storm': '플라스마 스톰',
  'Plasma Freeze': '플라스마 프리즈',
  'Plasma Blast': '플라스마 블래스트',
  'Legendary Treasures': '레전더리 트레저',
  'BW Black Star Promos': 'BW 블랙스타 프로모',
  // HeartGold & SoulSilver
  'HeartGold SoulSilver': '하트골드 소울실버',
  'Unleashed': '언리쉬드',
  'Undaunted': '언돈티드',
  'Triumphant': '트라이엄펀트',
  'HGSS Black Star Promos': 'HGSS 블랙스타 프로모',
  'Call of Legends': '콜 오브 레전드',
  // Platinum
  'Platinum': '플래티넘',
  'Rising Rivals': '라이징 라이벌',
  'Supreme Victors': '슈프림 빅터',
  'Arceus': '아르세우스',
  'Pokémon Rumble': '포켓몬 럼블',
  // Diamond & Pearl
  'Diamond & Pearl': '다이아몬드 & 펄',
  'Mysterious Treasures': '미스테리어스 트레저',
  'Secret Wonders': '시크릿 원더',
  'Great Encounters': '그레이트 인카운터',
  'Majestic Dawn': '마제스틱 던',
  'Legends Awakened': '레전드 어웨이크닝',
  'Stormfront': '스톰프론트',
  'DP Black Star Promos': 'DP 블랙스타 프로모',
  // POP
  'POP Series 1': 'POP 시리즈 1',
  'POP Series 2': 'POP 시리즈 2',
  'POP Series 3': 'POP 시리즈 3',
  'POP Series 4': 'POP 시리즈 4',
  'POP Series 5': 'POP 시리즈 5',
  'POP Series 6': 'POP 시리즈 6',
  'POP Series 7': 'POP 시리즈 7',
  'POP Series 8': 'POP 시리즈 8',
  'POP Series 9': 'POP 시리즈 9',
  'Nintendo Black Star Promos': '닌텐도 블랙스타 프로모',
  // EX 시리즈 (일본판 ADV·PCG 블록에 대응 — 정식 한글명 있는 건 매칭)
  'Ruby & Sapphire': '루비 & 사파이어',
  'Sandstorm': '샌드스톰',
  'Dragon': '드래곤',
  'Team Magma vs Team Aqua': '마그마단 VS 아쿠아단',
  'Hidden Legends': '히든 레전드',
  'FireRed & LeafGreen': '전설의 비상',
  'Team Rocket Returns': '로켓단의 역습',
  'Deoxys': '창공의 격돌',
  'Emerald': '에메랄드',
  'Unseen Forces': '금의 하늘, 은의 바다',
  'Delta Species': '호론의 연구탑',
  'Legend Maker': '환상의 숲',
  'Holon Phantoms': '호론의 환영',
  'Crystal Guardians': '기적의 결정',
  'Dragon Frontiers': '최후의 공방',
  'Power Keepers': '파워 키퍼',
  // Trainer kits
  'EX trainer Kit (Latios)': 'EX 트레이너 키트 (라티오스)',
  'EX trainer Kit (Latias)': 'EX 트레이너 키트 (라티아스)',
  'EX trainer Kit 2 (Plusle)': 'EX 트레이너 키트 2 (플러시)',
  'EX trainer Kit 2 (Minun)': 'EX 트레이너 키트 2 (마이농)',
  // e-Card (일본판 e블록 대응)
  'Expedition Base Set': '기본확장팩',
  'Best of game': '베스트 오브 게임',
  'Aquapolis': '아쿠아폴리스',
  'Skyridge': '스카이릿지',
  // 초기 시리즈
  'Legendary Collection': '레전더리 컬렉션',
  'Neo Genesis': '금, 은, 신세계로...',
  'Neo Discovery': '유적을 넘어서...',
  'Southern Islands': '남쪽 섬',
  'Neo Revelation': '각성하는 전설',
  'Neo Destiny': '어둠, 그리고 빛으로...',
  'Gym Heroes': '리더스 스타디움',
  'Gym Challenge': '어둠에서의 도전',
  'Base Set': '베이스 세트',
  'Jungle': '포켓몬 정글',
  'Wizards Black Star Promos': '위저드 블랙스타 프로모',
  'Fossil': '화석의 비밀',
  'Base Set 2': '베이스 세트 2',
  'Team Rocket': '로켓단',

  // 작가별 목록의 세트명은 다른 소스(scrydex)라 표기가 조금 다르다. 같은 세트가 화면마다
  // 다른 이름으로 보이지 않게 별칭을 함께 둔다(한글명은 위 정식 항목과 동일하게 맞춤).
  'HeartGold & SoulSilver': '하트골드 소울실버',
  'HS—Triumphant': '트라이엄펀트',
  'HS—Unleashed': '언리쉬드',
  'HS—Undaunted': '언돈티드',
  'Base': '베이스 세트',
  'Best of Game': '베스트 오브 게임',
  'Pokémon Futsal Collection': '포켓몬 풋살 2020',
  'Scarlet & Violet Black Star Promos': 'SVP 블랙스타 프로모',
  'Scarlet & Violet Promos': 'SVP 블랙스타 프로모',
  'Celebrations: Classic Collection': '셀레브레이션즈: 클래식 컬렉션',
  'EX Trainer Kit Latios': 'EX 트레이너 키트 (라티오스)',
  'EX Trainer Kit Latias': 'EX 트레이너 키트 (라티아스)',
  'EX Trainer Kit 2 Plusle': 'EX 트레이너 키트 2 (플러시)',
  'EX Trainer Kit 2 Minun': 'EX 트레이너 키트 2 (마이농)',
};

// 맥도날드·POP 등은 규칙적이라 접두 변환으로 처리(개별 매핑 누락 방지).
export function koSetName(name: string): string {
  if (SET_KO[name]) return SET_KO[name];
  const mcd = name.match(/^McDonald's Collection (\d{4})$/);
  if (mcd) return `맥도날드 컬렉션 ${mcd[1]}`;
  return name;
}
