import PPT_SET_KO from "../data/setNameKoPpt.json" with { type: "json" };

// 영문판·Pocket 세트의 공식 한글명(영어명 그대로면 한글 사이트에서 어색).
// 키는 영어 세트명 — 원본 name은 그대로 둬서 영어 검색도 계속 되게 한다.
// 세트별 목록(SetsView)과 작가별 목록(ArtistsView)이 같은 세트를 같은 한글명으로
// 보여줘야 해서 공용 모듈로 뒀다. 두 화면 모두 지연 로딩이라 컴포넌트끼리 import하면
// 코드 분리가 깨지므로 lib에 둔다.
import { koreanizeEnglishCardName } from './koreanizeEnglishTitle.ts';

export const SET_KO: Record<string, string> = {
  // ── 덤프에서 새로 넣은 세트 213개(2026-08-09) ─────────────────────────────
  // 데이터에는 저쪽 원어를 두고 화면에는 여기 적힌 한글이 나간다.
  // ⚠️ 한국 미발매 세트라 공식 한글명이 없다 — 표준 외래어 표기·직역으로 옮긴 뒤
  //    사장님이 하나씩 확인해 확정한 것이다(포켓몬 이름은 우리 카드 사전 그대로).
  'SVM: Generations Start Decks': 'SVM 제너레이션즈 스타트 덱',
  'Base Set (Shadowless)': '베이스 세트 (섀도우리스)',
  'Pt3: Beat of the Frontier': 'Pt3 프론티어의 고동',
  'Pt1: Galactic\'s Conquest': 'Pt1 갤럭틱의 정복',
  'Intense Fight in the Destroyed Sky': '무너진 하늘의 격전',
  'Pt4: Advent of Arceus': 'Pt4 아르세우스의 강림',
  'Pt2: Bonds to the End of Time': 'Pt2 시간의 끝의 인연',
  'BW9: Megalo Cannon': 'BW9 메갈로 캐논',
  'Undone Seal': '풀려난 봉인',
  'Magma VS Aqua: Two Ambitions': '마그마단 VS 아쿠아단 두 개의 야망',
  'BW7: Plasma Gale': 'BW7 플라즈마 게일',
  'L-P: Legends Promos': 'L-P 레전드 프로모',
  'BW4: Dark Rush': 'BW4 다크 러시',
  'BW2: Red Collection': 'BW2 레드 컬렉션',
  'L1: HeartGold Collection': 'L1 하트골드 컬렉션',
  'BW6: Cold Flare': 'BW6 콜드 플레어',
  'BW6: Freeze Bolt': 'BW6 프리즈 볼트',
  'BW8: Spiral Force': 'BW8 스파이럴 포스',
  'BW8: Thunder Knuckle': 'BW8 썬더 너클',
  'BW3: Psycho Drive': 'BW3 사이코 드라이브',
  'BW3: Hail Blizzard': 'BW3 헤일 블리자드',
  'BW1: Black Collection': 'BW1 블랙 컬렉션',
  'BW5: Dragon Blast': 'BW5 드래곤 블라스트',
  'BW5: Dragon Blade': 'BW5 드래곤 블레이드',
  'BW1: White Collection': 'BW1 화이트 컬렉션',
  'Rulers of the Heavens': '하늘의 지배자',
  'Miracle of the Desert': '사막의 기적',
  'SV: Ancient Koraidon ex Starter Deck & Build Set': 'SV 에인션트 코라이돈 ex 스타트 덱 & 빌드 세트',
  'SV: Future Miraidon ex Starter Deck & Build Set': 'SV 퓨처 미라이돈 ex 스타트 덱 & 빌드 세트',
  'Everyone\'s Exciting Battle': '모두의 익사이팅 배틀',
  'Master Deck Build Box EX': '마스터 덱 빌드 박스 EX',
  'SVN: Battle Partners Deck Build Box': 'SVN 배틀 파트너즈 덱 빌드 박스',
  'smG: Ultra Sun & Ultra Moon Deck Build Boxes': 'smG 울트라 썬 & 울트라 문 덱 빌드 박스',
  'LL: Lost Link': 'LL 로스트 링크',
  'XY Beginning Set': 'XY 비기닝 세트',
  'SV: Ruler of the Black Flame Deck Build Box': 'SV 흑염의 지배자 덱 빌드 박스',
  'smJ: Tag Team GX Premium Trainer Box': 'smJ 태그 팀 GX 프리미엄 트레이너 박스',
  'sF: Single Strike & Rapid Strike Premium Trainer Boxes': 'sF 싱글 스트라이크 & 래피드 스트라이크 프리미엄 트레이너 박스',
  'PLAY Promotional cards': '플레이 프로모 카드',
  'smM: Tag Team GX Starter Sets': 'smM 태그 팀 GX 스타트 세트',
  'WCS23: 2023 World Championships Yokohama Deck: Pikachu': 'WCS23 2023 월드 챔피언십 요코하마 덱: 피카츄',
  'Intro Pack Neo (Chikorita)': '인트로 팩 네오 (치코리타)',
  'Intro Pack Neo (Totodile)': '인트로 팩 네오 (리아코)',
  'Pokemon-e Starter Deck': '포켓몬e 스타트 덱',
  'smN: Tag Team GX Deck Build Box': 'smN 태그 팀 GX 덱 빌드 박스',
  'Shiny Collection': '샤이니 컬렉션',
  'Shockwave! Tyranitar ex Constructed Standard Deck': '충격파! 마기라스 ex 구축 스탠다드 덱',
  'Imprison! Gardevoir ex Constructed Standard Deck': '주박! 가디안 ex 구축 스탠다드 덱',
  'XYC: Super Legend Set: Xerneas-EX & Yveltal-EX': 'XYC 슈퍼 레전드 세트: 제르네아스 EX & 이벨타르 EX',
  'SS: Inteleon VMAX High-Class Deck': 'SS 인텔리레온 VMAX High-Class 덱',
  'MP1: Start Deck 100 Battle Collection CoroCiao Version': 'MP1 스타트 덱 100 배틀 컬렉션 코로챠오 버전',
  'Movie Commemoration Random Pack': '극장판 기념 랜덤 팩',
  'SV: Terastal Charizard ex Battle Master Deck': 'SV 테라스탈 리자몽 ex 배틀 마스터 덱',
  'smE: Solgaleo-GX & Lunala-GX Legendary Starter Set': 'smE 솔가레오 GX & 루나아라 GX 레전더리 스타트 세트',
  'smC: Tapu Bulu-GX Enhanced Starter Set': 'smC 카푸 브루루 GX 강화 스타트 세트',
  'Movie Commemoration VS Pack: Aura\'s Lucario': '극장판 기념 VS 팩: 오라의 루카리오',
  'SV: ex Starter Set Marnie\'s Morpeko & Grimmsnarl ex': 'SV ex 스타트 세트 마리의 모르페코 & 오롱털 ex',
  'SS: Gengar VMAX High-Class Deck': 'SS 팬텀 VMAX High-Class 덱',
  'Dragon Selection': '드래곤 셀렉션',
  'SV: Mewtwo ex Terastal Starter Set': 'SV 뮤츠 ex 테라스탈 스타트 세트',
  'SV: Skeledirge ex Terastal Starter Set': 'SV 라우드본 ex 테라스탈 스타트 세트',
  'ME: 30th Celebration': 'ME 30th 셀러브레이션',
  'L2: Steelix Constructed Standard Deck': 'L2 강철톤 구축 스탠다드 덱',
  'Movie Commemoration VS Pack': '극장판 기념 VS 팩',
  'Torchic Constructed Starter Deck': '아차모 구축 스타트 덱',
  'Mudkip Constructed Starter Deck': '물짱이 구축 스타트 덱',
  'Treecko Constructed Starter Deck': '나무지기 구축 스타트 덱',
  'Movie Commemoration VS Pack: Sea\'s Manaphy': '극장판 기념 VS 팩: 바다의 마나피',
  'Metagross Constructed Starter Deck': '메타그로스 구축 스타트 덱',
  'Salamence Constructed Starter Deck': '보만다 구축 스타트 덱',
  'SV: ex Starter Set Steven\'s Beldum & Metagross ex': 'SV ex 스타트 세트 성호의 메탕 & 메타그로스 ex',
  'L2: Tyranitar Constructed Standard Deck': 'L2 마기라스 구축 스탠다드 덱',
  'Flygon Constructed Starter Deck': '플라이곤 구축 스타트 덱',
  'XYG: Zygarde-EX Perfect Battle Deck': 'XYG 지가르데 EX 퍼펙트 배틀 덱',
  'XYB: Dialga-EX + Aegislash-EX Hyper Metal Chain Deck': 'XYB 디아루가 EX + 킬가르도 EX 하이퍼 메탈 체인 덱',
  'McDonald\'s Pokémon-e Minimum Pack': '맥도날드 포켓몬-e 미니멈 팩',
  'Theater Limited VS Pack': '극장 리미티드 VS 팩',
  'Random Constructed Starter Decks (Venusaur/Charizard/Blastoise)': '랜덤 구축 스타트 덱 (이상해꽃/리자몽/거북왕)',
  'Melee! Pokemon Scramble': '난투! 포켓몬 스크램블',
  'Blastoise + Kyurem-EX Combo Deck': '거북왕 + 큐레무 EX 콤보 덱',
  'BKW: White Kyurem-EX Battle Strength Deck': 'BKW 화이트 큐레무 EX 배틀 강화 덱',
  'BKZ: Zekrom-EX Battle Strength Deck': 'BKZ 제크로무 EX 배틀 강화 덱',
  'BKR: Reshiram-EX Battle Strength Deck': 'BKR 레시라무 EX 배틀 강화 덱',
  'BKB: Black Kyurem-EX Battle Strength Deck': 'BKB 블랙 큐레무 EX 배틀 강화 덱',
  'Team Plasma\'s Powered Half Deck': '팀 플라즈마의 파워드 하프 덱',
  'Typhlosion Constructed Starter Deck': '블레이범 구축 스타트 덱',
  'Earth\'s Groudon ex Constructed Starter Deck': '대지의 그란돈 ex 구축 스타트 덱',
  'Feraligatr Constructed Starter Deck': '장크로다일 구축 스타트 덱',
  'Mirage\'s Mew Constructed Starter Deck': '미라주의 뮤 구축 스타트 덱',
  'Meganium Constructed Starter Deck': '메가니움 구축 스타트 덱',
  'Ocean\'s Kyogre ex Constructed Starter Deck': '오션의 가이오가 ex 구축 스타트 덱',
  'XYF: Golduck BREAK + Palkia-EX Combo Deck': 'XYF 골덕 BREAK + 펄기아 EX 콤보 덱',
  'Lightning Quick Construction Pack': '번개 퀵 구축 팩',
  'Holon Research Tower Water Quarter Deck': '홀론 리서치 타워 물 쿼터 덱',
  'Rayquaza Constructed Starter Deck': '레쿠쟈 구축 스타트 덱',
  'Fire Quick Construction Pack': '불꽃 퀵 구축 팩',
  'Psychic Quick Construction Pack': '초 퀵 구축 팩',
  'Grass Quick Construction Pack': '풀 퀵 구축 팩',
  'Holon Research Tower Fire Quarter Deck': '홀론 리서치 타워 불꽃 쿼터 덱',
  'Fighting Quick Construction Pack': '격투 퀵 구축 팩',
  'Deoxys Constructed Starter Deck': '테오키스 구축 스타트 덱',
  'Water Quick Construction Pack': '물 퀵 구축 팩',
  'Leafeon vs Metagross Expert Deck (Leafeon)': '리피아 vs 메타그로스 엑스퍼트 덱 (리피아)',
  'Keldeo Battle Strength Deck': '케르디오 배틀 강화 덱',
  'Holon Research Tower Lightning Quarter Deck': '홀론 리서치 타워 번개 쿼터 덱',
  'Leafeon vs Metagross Expert Deck (Metagross)': '리피아 vs 메타그로스 엑스퍼트 덱 (메타그로스)',
  'BK: Virizion Battle Strength Deck': 'BK 비리디온 배틀 강화 덱',
  'BK: Cobalion Battle Strength Deck': 'BK 코바르온 배틀 강화 덱',
  'BK: Terrakion Battle Strength Deck': 'BK 테라키온 배틀 강화 덱',
  'smF: Ultra Sun & Ultra Moon Premium Trainer Box': 'smF 울트라 썬 & 울트라 문 프리미엄 트레이너 박스',
  'BW: Extra Regulation Box': 'BW 엑스트라 레귤레이션 박스',
  'sPD: Deoxys VSTAR & VMAX High-Class Deck': 'sPD 테오키스 VSTAR & VMAX High-Class 덱',
  'sPZ: Zeraora VSTAR & VMAX High-Class Deck': 'sPZ 제라오라 VSTAR & VMAX High-Class 덱',
  'SNP: Raichu BREAK Evolution Pack': 'SNP 라이츄 BREAK 에볼루션 팩',
  'SNP: Noivern BREAK Evolution Pack': 'SNP 음번 BREAK 에볼루션 팩',
  'First Partner Collection 2026': '퍼스트 파트너 컬렉션 2026',
  '11th Movie Commemoration Set': '11th 극장판 기념 세트',
  'PokePark Forest': '포켓파크 포레스트',
  'CS1: Journey Partners Collection Sheet': 'CS1 저니 파트너즈 컬렉션 시트',
  'Sun & Moon Unnumbered Energies': '썬 & 문 번호없는 에너지',
  'sN: Start Deck 100 CoroCoro Comic Version': 'sN 스타트 덱 100 코로코로 코믹 버전',
  'Kids WB Promos': '키즈 WB 프로모',
  'sp4: Eevee Heroes VMAX Special Set': 'sp4 이브이 히어로즈 VMAX 스페셜 세트',
  'Mega Evolution Unnumbered Energies': '메가 에볼루션 번호없는 에너지',
  'e-Reader Sample Cards': 'e리더 샘플 카드',
  'SI: Start Deck 100': 'SI 스타트 덱 100',
  'PCG-P Promotional cards': 'PCG-P 프로모 카드',
  'SV: ex Start Decks': 'SV ex 스타트 덱',
  'smH: GX Starter Decks': 'smH GX 스타트 덱',
  'DP-P Promotional cards': 'DP-P 프로모 카드',
  'sD: V Starter Decks': 'sD V 스타트 덱',
  'BREAK Starter Pack': 'BREAK 스타트 팩',
  'Battle Academy': '배틀 아카데미',
  'ADV-P Promotional cards': 'ADV-P 프로모 카드',
  'sH: Sword & Shield Family Pokemon Card Game': 'sH 소드 & 실드 패밀리 포켓몬 카드 게임',
  'smA: Sun & Moon Starter Set': 'smA 썬 & 문 스타트 세트',
  'smL: Sun & Moon Family Pokemon Card Game': 'smL 썬 & 문 패밀리 포켓몬 카드 게임',
  'ADV Expansion Pack': 'ADV 확장 팩',
  'DPt-P Promotional cards': 'DPt-P 프로모 카드',
  'P Promotional cards': 'P 프로모 카드',
  'Battle Academy 2024': '배틀 아카데미 2024',
  'smK: Trainer Battle Decks': 'smK 트레이너 배틀 덱',
  'SV: Premium Trainer Box ex': 'SV 프리미엄 트레이너 박스 ex',
  's8a-P: Promo Card Pack 25th Anniversary Edition': 's8a-P 프로모 카드 팩 25th 애니버서리 에디션',
  'T Promotional cards': 'T 프로모 카드',
  'sA: Lightning Starter Set V': 'sA 번개 스타트 세트 V',
  'sA: Fighting Starter Set V': 'sA 격투 스타트 세트 V',
  'sB: Sword & Shield Premium Trainer Box': 'sB 소드 & 실드 프리미엄 트레이너 박스',
  'sA: Fire Starter Set V': 'sA 불꽃 스타트 세트 V',
  'sA: Water Starter Set V': 'sA 물 스타트 세트 V',
  'sA: Grass Starter Set V': 'sA 풀 스타트 세트 V',
  's8a-G: 25th Anniversary Golden Box': 's8a-G 25th 애니버서리 골든 박스',
  'sp5: V-UNION Special Card Sets': 'sp5 V-UNION 스페셜 카드 세트',
  'World Champions Pack': '월드 챔피언 팩',
  'sK: VSTAR Premium Trainer Box': 'sK VSTAR 프리미엄 트레이너 박스',
  'Master Kit (Side Deck)': '마스터 킷 (사이드 덱)',
  'sp2: VMAX Special Set': 'sp2 VMAX 스페셜 세트',
  'PPP Promotional cards': 'PPP 프로모 카드',
  'SV: ex Special Set': 'SV ex 스페셜 세트',
  'sp6: VSTAR Special Set': 'sp6 VSTAR 스페셜 세트',
  'J Promotional cards': 'J 프로모 카드',
  'smB: Premium Trainer Box': 'smB 프리미엄 트레이너 박스',
  'SM1+: Sun & Moon': 'SM1+ 썬 & 문',
  'SV: Venusaur, Charizard & Blastoise Special Deck Set': 'SV 이상해꽃, 리자몽 & 거북왕 스페셜 덱 세트',
  'Intro Pack (Squirtle)': '인트로 팩 (꼬부기)',
  'Intro Pack (Bulbasaur)': '인트로 팩 (이상해씨)',
  'smI: Flareon-GX, Vaporeon-GX & Jolteon-GX Starter Sets': 'smI 부스터 GX, 샤미드 GX & 쥬피썬더 GX 스타트 세트',
  'Pokemon TCG Classic: Charizard': '포켓몬 TCG 클래식: 리자몽',
  'Pokemon TCG Classic: Blastoise': '포켓몬 TCG 클래식: 거북왕',
  'Pokemon TCG Classic: Venusaur': '포켓몬 TCG 클래식: 이상해꽃',
  'XYH: M Audino-EX Mega Battle Deck': 'XYH M 다부니 EX 메가 배틀 덱',
  'SV: ex Starter Set Sprigatito & Lucario ex': 'SV ex 스타트 세트 나오하 & 루카리오 ex',
  'SV: ex Starter Set Quaxly & Mimikyu ex': 'SV ex 스타트 세트 꾸왁스 & 따라큐 ex',
  'MBG: MEGA Starter Set Mega Gengar ex': 'MBG 메가 스타트 세트 메가 팬텀 ex',
  'MBD: MEGA Starter Set Mega Diancie ex': 'MBD 메가 스타트 세트 메가 디안시 ex',
  'XYA: M Charizard-EX Mega Battle Deck': 'XYA M 리자몽 EX 메가 배틀 덱',
  'Battle Theme Deck: Victini': '배틀 테마 덱: 비크티니',
  'sC: Charizard Starter Set VMAX': 'sC 리자몽 스타트 세트 VMAX',
  'sC2: Charizard Starter Set VMAX 2': 'sC2 리자몽 스타트 세트 VMAX 2',
  'sEF: Venusaur Starter Set VMAX': 'sEF 이상해꽃 스타트 세트 VMAX',
  'SV: ex Starter Set Fuecoco & Ampharos ex': 'SV ex 스타트 세트 뜨아거 & 전룡 ex',
  'sC: Grimmsnarl Starter Set VMAX': 'sC 오롱털 스타트 세트 VMAX',
  'sEK: Blastoise Starter Set VMAX': 'sEK 거북왕 스타트 세트 VMAX',
  'MEE: Starter Set ex Eevee ex': 'MEE 스타트 세트 ex 이브이 ex',
  'MEZ: Starter Set ex Zoroark ex': 'MEZ 스타트 세트 ex 조로아크 ex',
  'SV: Chien-Pao ex Battle Master Deck': 'SV 파오젠 ex 배틀 마스터 덱',
  'MEM: Starter Set ex Meowscarada ex': 'MEM 스타트 세트 ex 마스카나 ex',
  'XYD: M Rayquaza-EX Mega Battle Deck': 'XYD M 레쿠쟈 EX 메가 배틀 덱',
  'Pikachu World Collection Promos': '피카츄 월드 컬렉션 프로모',
  'Arceus LV.X Deck: Lightning & Psychic': '아르세우스 LV.X 덱: 번개 & 초',
  's0: Charizard VSTAR vs Rayquaza VMAX Special Deck Set': 's0 리자몽 VSTAR vs 레쿠쟈 VMAX 스페셜 덱 세트',
  'Arceus LV.X Deck: Grass & Fire': '아르세우스 LV.X 덱: 풀 & 불꽃',
  'sLD: Darkrai Starter Set VSTAR': 'sLD 다크라이 스타트 세트 VSTAR',
  'SV: ex Starter Set Pikachu ex & Pawmot': 'SV ex 스타트 세트 피카츄 ex & 빠르모트',
  'Hydreigon Half Deck': '삼삼드래 하프 덱',
  'sJ: Zacian & Zamazenta vs Eternatus Special Deck Set': 'sJ 자시안 & 자마젠타 vs 무한다이노 스페셜 덱 세트',
  'Garchomp Half Deck': '한카리아스 하프 덱',
  'Yveltal Half Deck': '이벨타르 하프 덱',
  'Xerneas Half Deck': '제르네아스 하프 덱',
  'Entry Pack DPt (Giratina)': '엔트리 팩 DPt (기라티나)',
  'Entry Pack DPt (Palkia)': '엔트리 팩 DPt (펄기아)',
  'Entry Pack DPt (Dialga)': '엔트리 팩 DPt (디아루가)',
  'smP1: Rockruff Full Power Deck': 'smP1 암멍이 풀 파워 덱',
  'PtS: Shaymin LV.X Collection Pack': 'PtS 쉐이미 LV.X 컬렉션 팩',
  'PtM: Mewtwo LV.X Collection Pack': 'PtM 뮤츠 LV.X 컬렉션 팩',
  'PtR: Regigigas LV.X Collection Pack': 'PtR 레지기가스 LV.X 컬렉션 팩',
  'Battle Starter Deck (Raichu)': '배틀 스타트 덱 (라이츄)',
  'sLL: Lucario Starter Set VSTAR': 'sLL 루카리오 스타트 세트 VSTAR',
  'Battle Starter Deck (Blastoise)': '배틀 스타트 덱 (거북왕)',
  'Battle Starter Deck (Torterra)': '배틀 스타트 덱 (토대부기)',
  'Master Kit (Bulbasaur)': '마스터 킷 (이상해씨)',
  'Battle Starter Deck (Magmortar)': '배틀 스타트 덱 (마그마번)',
  'sp1: Zacian + Zamazenta Box': 'sp1 자시안 + 자마젠타 박스',

  // Pokémon TCG Pocket (한국어판 게임 공식 확장팩명, 나무위키 대조)
  'Genetic Apex': '최강의 유전자',
  'Mythical Island': '환상이 있는 섬',
  'Space-Time Smackdown': '시공의 격투',
  'Triumphant Light': '초극의 빛',
  'Shining Revelry': '샤이닝 하이',
  'Celestial Guardians': '쌍천의 수호자',
  'Extradimensional Crisis': '이차원 크라이시스',
  'Eevee Grove': '이브이 가든',
  'Wisdom of Sea and Sky': '하늘과 바다의 인도',
  'Secluded Springs': '미지의 수역',
  'Mega Rising': '메가라이징',
  'Crimson Blaze': '홍련 블레이즈',
  'Fantastical Parade': '몽환 퍼레이드',
  'Paldean Wonders': '팔데아의 기적',
  'Promos-A': '프로모 카드 A',

  // ── 물리 영문판(EN) ──
  // ⚠️ 영문판은 **영문판 이름을 소리 나는 대로** 적는다(운영자 지시 2026-08-05).
  //    예전엔 "일본판과 1:1 대응하면 정식 한글명"이었는데, 1:1이라는 판단이 틀렸다.
  //    Surging Sparks는 영문판 252장, 초전브레이커는 일본판 138장이고 같은 번호에
  //    다른 카드가 들어 있다(3번: 일본판 아이언트 ex / 영문판 나시). 영문판은 일본판
  //    두세 개를 합쳐 내기 때문이다. 다른 상품에 같은 이름을 붙이면, 목록을 연 사람이
  //    카드가 다른 걸 보고 우리가 틀렸다고 생각한다.
  //    포켓몬 이름이 들어간 것만 정식 한글명을 쓴다(Deoxys→테오키스).
  // Mega Evolution (EN 메가 시리즈)
  'Mega Evolution': '메가 에볼루션',
  'Phantasmal Flames': '팬타스말 플레임즈',
  'Ascended Heroes': '어센디드 히어로즈',
  'Perfect Order': '퍼펙트 오더',
  'Chaos Rising': '카오스 라이징',
  'Pitch Black': '피치 블랙',
  // Scarlet & Violet
  'Scarlet & Violet': '스칼렛 & 바이올렛',
  'Paldea Evolved': '팔데아 이볼브드',
  'Obsidian Flames': '옵시디언 플레임즈',
  '151': '151',
  'Paradox Rift': '패러독스 리프트',
  'Paldean Fates': '팔데안 페이츠',
  'Temporal Forces': '템포럴 포시스',
  'Twilight Masquerade': '트와일라잇 마스커레이드',
  'Shrouded Fable': '슈라우디드 페이블',
  'Stellar Crown': '스텔라 크라운',
  'Surging Sparks': '서징 스파크스',
  'Prismatic Evolutions': '프리즈매틱 이볼루션즈',
  'Journey Together': '저니 투게더',
  'Destined Rivals': '데스틴드 라이벌즈',
  'Black Bolt': '블랙 볼트',
  'White Flare': '화이트 플레어',
  'SVP Black Star Promos': 'SVP 블랙스타 프로모',
  // Sword & Shield
  'Sword & Shield': '소드 & 실드',
  'Rebel Clash': '리벨 클래시',
  'Darkness Ablaze': '다크니스 어블레이즈',
  "Champion's Path": '챔피언스 패스',
  'Vivid Voltage': '비비드 볼티지',
  'Shining Fates': '샤이닝 페이츠',
  'Shining Fates Shiny Vault': '샤이닝 페이츠 샤이니 볼트',
  'Battle Styles': '배틀 스타일즈',
  'Chilling Reign': '칠링 레인',
  'Evolving Skies': '이볼빙 스카이즈',
  'Celebrations': '셀레브레이션즈',
  'Fusion Strike': '퓨전 스트라이크',
  'Brilliant Stars': '브릴리언트 스타즈',
  'Brilliant Stars Trainer Gallery': '브릴리언트 스타즈 트레이너 갤러리',
  'Astral Radiance': '아스트랄 라디언스',
  'Astral Radiance Trainer Gallery': '아스트랄 라디언스 트레이너 갤러리',
  'Pokémon GO': '포켓몬 GO',
  // 상품 이름이 아니라 원본(TCGdex)이 묶어 둔 자루 이름이다. 그대로 두면 목록에 영어만 뜬다.
  'Miscellaneous Promos': '기타 프로모',
  'Lost Origin': '로스트 오리진',
  'Lost Origin Trainer Gallery': '로스트 오리진 트레이너 갤러리',
  'Silver Tempest': '실버 템페스트',
  'Silver Tempest Trainer Gallery': '실버 템페스트 트레이너 갤러리',
  'Crown Zenith': '크라운 제니스',
  'Crown Zenith Galarian Gallery': '크라운 제니스 가라르 갤러리',
  'Pokémon Futsal 2020': '포켓몬 풋살 2020',
  'SWSH Black Star Promos': 'SWSH 블랙스타 프로모',
  // Sun & Moon
  'Sun & Moon': '썬 & 문',
  'Guardians Rising': '가디언즈 라이징',
  'Burning Shadows': '버닝 섀도우스',
  'Shining Legends': '샤이닝 레전즈',
  'Crimson Invasion': '크림슨 인베이전',
  'Ultra Prism': '울트라 프리즘',
  'Forbidden Light': '포비든 라이트',
  'Celestial Storm': '셀레스티얼 스톰',
  'Dragon Majesty': '드래곤 마제스티',
  'Lost Thunder': '로스트 썬더',
  'Team Up': '팀 업',
  'Detective Pikachu': '디텍티브 피카츄',
  'Unbroken Bonds': '언브로큰 본즈',
  'Unified Minds': '유니파이드 마인즈',
  'Hidden Fates': '히든 페이츠',
  'Hidden Fates Shiny Vault': '히든 페이츠 샤이니 볼트',
  'Cosmic Eclipse': '코스믹 이클립스',
  'SM Black Star Promos': 'SM 블랙스타 프로모',
  // XY
  'XY': 'XY',
  'Kalos Starter Set': '칼로스 스타터 세트',
  'Flashfire': '플래시파이어',
  'Furious Fists': '퓨리어스 피스츠',
  'Phantom Forces': '팬텀 포시스',
  'Primal Clash': '프라이멀 클래시',
  'Double Crisis': '더블 크라이시스',
  'Roaring Skies': '로어링 스카이즈',
  'Ancient Origins': '에인션트 오리진스',
  'BREAKthrough': '브레이크스루',
  'BREAKpoint': '브레이크포인트',
  'Generations': '제너레이션즈',
  'Fates Collide': '페이츠 콜라이드',
  'Steam Siege': '스팀 시즈',
  'Evolutions': '이볼루션즈',
  'XY Black Star Promos': 'XY 블랙스타 프로모',
  // Black & White
  'Black & White': '블랙 & 화이트',
  'Emerging Powers': '이머징 파워스',
  'Noble Victories': '노블 빅토리즈',
  'Next Destinies': '넥스트 데스티니즈',
  'Dark Explorers': '다크 익스플로러스',
  'Dragons Exalted': '드래곤즈 이그절티드',
  'Dragon Vault': '드래곤 볼트',
  'Boundaries Crossed': '바운더리즈 크로스드',
  'Plasma Storm': '플라스마 스톰',
  'Plasma Freeze': '플라스마 프리즈',
  'Plasma Blast': '플라스마 블래스트',
  'Legendary Treasures': '레전더리 트레저스',
  'BW Black Star Promos': 'BW 블랙스타 프로모',
  // HeartGold & SoulSilver
  'HeartGold SoulSilver': '하트골드 소울실버',
  'Unleashed': '언리쉬드',
  'Undaunted': '언돈티드',
  'Triumphant': '트라이엄펀트',
  'HGSS Black Star Promos': 'HGSS 블랙스타 프로모',
  'Call of Legends': '콜 오브 레전즈',
  // Platinum
  'Platinum': '플래티넘',
  'Rising Rivals': '라이징 라이벌스',
  'Supreme Victors': '슈프림 빅터스',
  'Arceus': '아르세우스',
  'Pokémon Rumble': '포켓몬 럼블',
  // Diamond & Pearl
  'Diamond & Pearl': '다이아몬드 & 펄',
  'Mysterious Treasures': '미스테리어스 트레저스',
  'Secret Wonders': '시크릿 원더스',
  'Great Encounters': '그레이트 인카운터스',
  'Majestic Dawn': '마제스틱 던',
  'Legends Awakened': '레전즈 어웨이크드',
  'Stormfront': '스톰프론트',
  'DP Black Star Promos': 'DP 블랙스타 프로모',
  // POP
  'POP Series 1': 'POP 시리즈 1',
  'POP Series 2': 'POP 시리즈 2',
  'POP Series 3': 'POP 시리즈 3',
  'POP Series 4': 'POP 시리즈 4',
  'POP Series 5': 'POP 시리즈 5',
  'POP Series 6': 'POP 시리즈 6',
  'POP Series 7': 'POP 시리즈 7',
  'POP Series 8': 'POP 시리즈 8',
  'POP Series 9': 'POP 시리즈 9',
  'Nintendo Black Star Promos': '닌텐도 블랙스타 프로모',
  // EX 시리즈 (일본판 ADV·PCG 블록에 대응 — 정식 한글명 있는 건 매칭)
  'Ruby & Sapphire': '루비 & 사파이어',
  'Sandstorm': '샌드스톰',
  'Dragon': '드래곤',
  'Team Magma vs Team Aqua': '마그마단 VS 아쿠아단',
  'Hidden Legends': '히든 레전즈',
  'FireRed & LeafGreen': '파이어레드 & 리프그린',
  'Team Rocket Returns': '팀 로켓 리턴즈',
  'Deoxys': '테오키스',
  'Emerald': '에메랄드',
  'Unseen Forces': '언신 포시즈',
  'Delta Species': '델타 스피시즈',
  'Legend Maker': '레전드 메이커',
  'Holon Phantoms': '홀론 팬텀즈',
  'Crystal Guardians': '크리스탈 가디언즈',
  'Dragon Frontiers': '드래곤 프론티어즈',
  'Power Keepers': '파워 키퍼스',
  // Trainer kits
  'EX trainer Kit (Latios)': 'EX 트레이너 키트 (라티오스)',
  'EX trainer Kit (Latias)': 'EX 트레이너 키트 (라티아스)',
  'EX trainer Kit 2 (Plusle)': 'EX 트레이너 키트 2 (플러시)',
  'EX trainer Kit 2 (Minun)': 'EX 트레이너 키트 2 (마이농)',
  // e-Card (일본판 e블록 대응)
  'Expedition Base Set': '엑스페디션 베이스 세트',
  'Best of game': '베스트 오브 게임',
  'Aquapolis': '아쿠아폴리스',
  'Skyridge': '스카이릿지',
  // 초기 시리즈
  'Legendary Collection': '레전더리 컬렉션',
  'Neo Genesis': '네오 제네시스',
  'Neo Discovery': '네오 디스커버리',
  'Southern Islands': '서던 아일랜즈',
  'Neo Revelation': '네오 레벌레이션',
  'Neo Destiny': '네오 데스티니',
  'Gym Heroes': '짐 히어로즈',
  'Gym Challenge': '짐 챌린지',
  'Base Set': '베이스 세트',
  'Jungle': '정글',
  'Wizards Black Star Promos': '위저드 블랙스타 프로모',
  'Fossil': '파슬',
  'Base Set 2': '베이스 세트 2',
  'Team Rocket': '팀 로켓',

  // 작가별 목록의 세트명은 다른 소스(scrydex)라 표기가 조금 다르다. 같은 세트가 화면마다
  // 다른 이름으로 보이지 않게 별칭을 함께 둔다(한글명은 위 정식 항목과 동일하게 맞춤).
  'HeartGold & SoulSilver': '하트골드 소울실버',
  'HS—Triumphant': '트라이엄펀트',
  'HS—Unleashed': '언리쉬드',
  'HS—Undaunted': '언돈티드',
  'Base': '베이스 세트',
  'Best of Game': '베스트 오브 게임',
  'Pokémon Futsal Collection': '포켓몬 풋살 2020',
  'Scarlet & Violet Black Star Promos': 'SVP 블랙스타 프로모',
  'Scarlet & Violet Promos': 'SVP 블랙스타 프로모',
  // 원본 세트명에 콜론이 없다. 콜론을 넣어 두면 영영 안 걸린다(en-cel25cc).
  // ⚠️ 이름 앞부분은 부모 세트와 똑같이 쓴다. 목록에서 나란히 서기 때문에 다르게 쓰면
  //    같은 시리즈로 안 보인다('Celebrations' = 셀레브레이션즈,
  //    'Unseen Forces' = 금의 하늘, 은의 바다).
  'Celebrations Classic Collection': '셀레브레이션즈 클래식 컬렉션',
  'Unseen Forces Unown Collection': '언신 포시즈 안농 컬렉션',
  'Poké Card Creator Pack': '포케 카드 크리에이터 팩',
  'Yellow A Alternate': '옐로 A 알터네이트',
  // 부모 세트('Mega Evolution' = 메가 에볼루션)와 앞부분을 맞춘다.
  'Mega Evolution Energy': '메가 에볼루션 에너지',
  'My First Battle': '마이 퍼스트 배틀',
  // 한글 이름이 없어 영어로 나오던 것들(2026-08-05). 트레이너 키트 괄호 안은
  // 포켓몬 정식 한글명이다 — 소리 나는 대로 적지 않는다(Sylveon은 실베온이 아니라 님피아).
  'MEP Black Star Promos': 'MEP 블랙스타 프로모',
  "McDonald's Collection 2011": '맥도날드 컬렉션 2011',
  "McDonald's Collection 2012": '맥도날드 컬렉션 2012',
  "McDonald's Collection 2014": '맥도날드 컬렉션 2014',
  "McDonald's Collection 2015": '맥도날드 컬렉션 2015',
  "McDonald's Collection 2016": '맥도날드 컬렉션 2016',
  "McDonald's Collection 2017": '맥도날드 컬렉션 2017',
  "McDonald's Collection 2018": '맥도날드 컬렉션 2018',
  "McDonald's Collection 2019": '맥도날드 컬렉션 2019',
  "McDonald's Collection 2021": '맥도날드 컬렉션 2021',
  "McDonald's Collection 2022": '맥도날드 컬렉션 2022',
  "McDonald's Collection 2023": '맥도날드 컬렉션 2023',
  "McDonald's Collection 2024": '맥도날드 컬렉션 2024',
  'XY trainer Kit (Bisharp)': 'XY 트레이너 키트 (절각참)',
  'XY trainer Kit (Latias)': 'XY 트레이너 키트 (라티아스)',
  'XY trainer Kit (Latios)': 'XY 트레이너 키트 (라티오스)',
  'XY trainer Kit (Noivern)': 'XY 트레이너 키트 (음번)',
  'XY trainer Kit (Pikachu Libre)': 'XY 트레이너 키트 (피카츄 리브레)',
  'XY trainer Kit (Suicune)': 'XY 트레이너 키트 (스이쿤)',
  'XY trainer Kit (Sylveon)': 'XY 트레이너 키트 (님피아)',
  'XY trainer Kit (Wigglytuff)': 'XY 트레이너 키트 (푸크린)',
  'SM trainer Kit (Alolan Raichu)': 'SM 트레이너 키트 (알로라 라이츄)',
  'SM trainer Kit (Lycanroc)': 'SM 트레이너 키트 (루가루암)',
  'HS trainer Kit (Gyarados)': 'HS 트레이너 키트 (갸라도스)',
  'HS trainer Kit (Raichu)': 'HS 트레이너 키트 (라이츄)',
  'DP trainer Kit (Lucario)': 'DP 트레이너 키트 (루카리오)',
  'DP trainer Kit (Manaphy)': 'DP 트레이너 키트 (마나피)',
  'BW trainer Kit (Excadrill)': 'BW 트레이너 키트 (몰드류)',
  'BW trainer Kit (Zoroark)': 'BW 트레이너 키트 (조로아크)',
  // 부모 세트('Scarlet & Violet' = 스칼렛 & 바이올렛)와 띄어쓰기를 맞춘다.
  'Scarlet & Violet Energy': '스칼렛 & 바이올렛 에너지',
  // 일본판이지만 이름이 영어로 붙어 있어 여기(영어 세트명 사전)로 들어온다(ja-S8a).
  '25th Anniversary': '25th 어니버서리 컬렉션',
  'EX Trainer Kit Latios': 'EX 트레이너 키트 (라티오스)',
  'EX Trainer Kit Latias': 'EX 트레이너 키트 (라티아스)',
  'EX Trainer Kit 2 Plusle': 'EX 트레이너 키트 2 (플러시)',
  'EX Trainer Kit 2 Minun': 'EX 트레이너 키트 2 (마이농)',
};

// 맥도날드·POP 등은 규칙적이라 접두 변환으로 처리(개별 매핑 누락 방지).
export function koSetName(name: string): string {
  // ⚠️ PPT로 도감을 갈아엎으며 세트 이름이 저쪽 원어가 됐다. 사장님이 540개를 하나씩
  //    확인해 확정한 한글 이름이 `setNameKoPpt.json`에 있다 — 그것을 먼저 본다.
  if ((PPT_SET_KO as Record<string, string>)[name]) return (PPT_SET_KO as Record<string, string>)[name];
  if (SET_KO[name]) return SET_KO[name];
  const mcd = name.match(/^McDonald's Collection (\d{4})$/);
  if (mcd) return `맥도날드 컬렉션 ${mcd[1]}`;
  // 트레이너킷은 "<시리즈> trainer Kit (<포켓몬>)" 꼴로 16개가 같은 모양이다.
  // 하나씩 적는 대신 규칙으로 잡는다. 괄호 안 포켓몬 이름은 영문 사전으로 바꾼다.
  const kit = name.match(/^(\w+) trainer Kit \(([^)]+)\)$/i);
  if (kit) return `${kit[1]} 트레이너킷 (${koreanizeEnglishCardName(kit[2])})`;
  // 블랙스타 프로모도 시리즈 코드만 다르다. 새 시리즈가 나와도 저절로 잡힌다.
  const promo = name.match(/^(\w+) Black Star Promos$/);
  if (promo) return `${promo[1]} 블랙스타 프로모`;
  return name;
}

// 시리즈 이름을 주소에 쓸 수 있는 꼴로 바꾼다("剣と盾" → "剣と盾", "Sword & Shield" → "sword-shield").
// 서버(server/index.ts의 /series/:slug)와 화면·사이트맵이 같은 규칙을 써야 주소가 맞는다.
export const serieSlug = (serie: string): string =>
  serie
    .toLowerCase()
    .replace(/[^\w가-힣ぁ-んァ-ヶー・一-鿿]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60) || 'etc';
